/**
 * The three legal documents in the footer: Privacy Policy, Terms and
 * Conditions, and the Customer Service Agreement. Formal legal Arabic, kept
 * clause-for-clause with the English so the two versions can be read side by
 * side.
 */
export const arLegal: Record<string, string> = {
  // --- headings ------------------------------------------------------------
  "Policy Statement": "بيان السياسة",
  "Policy Scope": "نطاق السياسة",
  "Share Information": "مشاركة المعلومات",
  "Collection and Storage of Information Automatically":
    "جمع المعلومات وتخزينها تلقائيًا",
  "Information Security": "أمن المعلومات",
  "Password Security": "أمن كلمة المرور",
  "Protection of personal information": "حماية المعلومات الشخصية",
  "Data Deletion and User Accounts": "حذف البيانات وحسابات المستخدمين",
  "Dubai Police App Permissions": "أذونات تطبيق شرطة دبي",
  "Amendment of Privacy Policy": "تعديل سياسة الخصوصية",
  Privacy: "الخصوصية",
  Copyrights: "حقوق النشر",
  Trademarks: "العلامات التجارية",
  "Disclaimer of Warranties": "إخلاء المسؤولية عن الضمانات",
  "Disclaimer of Liability": "إخلاء المسؤولية القانونية",
  "No Unlawful or Prohibited Use": "الاستخدام غير المشروع أو المحظور",
  "Possible Errors and Revisions": "الأخطاء المحتملة والتنقيحات",
  Modifications: "التعديلات",
  "Governing Law": "القانون الواجب التطبيق",
  "Virus protection": "الحماية من الفيروسات",
  "Settlement of Disputes Relating Electronic Payment":
    "تسوية المنازعات المتعلقة بالدفع الإلكتروني",

  // --- privacy policy ------------------------------------------------------
  'Dubai police is committed to protecting the rights of visitors to its Website and to maintaining the confidentiality of personal information that is used in this Website. Privacy Policy aims to clarify the approach of the Dubai Police, and the obligations; with respect to the collection, use, distribution, retention, destruction and dissemination (collectively called, "use" or "usage" or their derivatives) of personal information or data (collectively called, "data") which is collected on Dubai police eServices Website at ':
    "تلتزم شرطة دبي بحماية حقوق زوار موقعها الإلكتروني وبالحفاظ على سرية المعلومات الشخصية المستخدمة في هذا الموقع. وتهدف سياسة الخصوصية إلى توضيح نهج شرطة دبي والتزاماتها فيما يتعلق بجمع المعلومات أو البيانات الشخصية (ويُشار إليها مجتمعةً بـ«البيانات») واستخدامها وتوزيعها والاحتفاظ بها وإتلافها ونشرها (ويُشار إليها مجتمعةً بـ«الاستخدام» أو مشتقاته)، والتي تُجمع على موقع الخدمات الإلكترونية لشرطة دبي على ",
  "Privacy Policy, set forth in this document, applies to Dubai Police Website (www.dubaipolice.gov.ae) and to the information collected by this Site only. This Policy also applies to all employees of Dubai Police, apart from their place of work, and also to all the concerned suppliers’ employees, irrespective of the place of whoever manages Dubai Police Website, which can obtain personal data of the users.":
    "تسري سياسة الخصوصية الواردة في هذه الوثيقة على موقع شرطة دبي (www.dubaipolice.gov.ae) وعلى المعلومات التي يجمعها هذا الموقع فقط. كما تسري هذه السياسة على جميع منتسبي شرطة دبي أيًا كان مكان عملهم، وعلى جميع موظفي الموردين المعنيين، بصرف النظر عن مكان من يدير موقع شرطة دبي، ممن يمكنهم الاطلاع على البيانات الشخصية للمستخدمين.",
  "Any data required from the user, in this Website, will be used, exclusively, in accordance with the privacy policy set forth below. Dubai Police will never ask for any unnecessary data.":
    "تُستخدم أي بيانات تُطلب من المستخدم في هذا الموقع حصريًا وفقًا لسياسة الخصوصية الواردة أدناه. ولن تطلب شرطة دبي أي بيانات غير ضرورية.",
  "The information that Dubai Police may obtain from users of this website on the internet is treated with utmost privacy and confidentiality, and it is not disclosed to third parties except for legal, security, or awareness purposes.":
    "تُعامَل المعلومات التي قد تحصل عليها شرطة دبي من مستخدمي هذا الموقع بأقصى درجات الخصوصية والسرية، ولا يتم الإفصاح عنها للغير إلا لأغراض قانونية أو أمنية أو توعوية.",
  'Dubai Police Website includes public pages that can be browsed by all users, without having to provide any personal data with the exception of data collected by cookies when used (see details below). The Site also contains secured pages that require registration to be accessed, using the form "request a user registration", in the open public pages.':
    "يتضمن موقع شرطة دبي صفحات عامة يمكن لجميع المستخدمين تصفحها دون الحاجة إلى تقديم أي بيانات شخصية، باستثناء البيانات التي تجمعها ملفات تعريف الارتباط عند استخدامها (انظر التفاصيل أدناه). كما يحتوي الموقع على صفحات مؤمّنة يتطلب الوصول إليها التسجيل عبر نموذج «طلب تسجيل مستخدم» في الصفحات العامة المفتوحة.",
  "Dear user, if you wish to provide us with information about you by sending an email or fill the form for your personal information and submit it to us, via our Website, we use these information to respond to your message and to help us provide you with the information you requested. If you send your data summary across our Website, we use your personal data for employment purpose only and not for other purposes.":
    "عزيزي المستخدم، إذا رغبت في تزويدنا بمعلومات عنك عبر إرسال بريد إلكتروني أو تعبئة نموذج معلوماتك الشخصية وإرساله إلينا عبر موقعنا، فإننا نستخدم هذه المعلومات للرد على رسالتك ولمساعدتنا في تزويدك بالمعلومات التي طلبتها. وإذا أرسلت سيرتك الذاتية عبر موقعنا، فإننا نستخدم بياناتك الشخصية لأغراض التوظيف فقط دون غيرها.",
  "Dear user, when browsing Dubai Police Website, we will collect and store certain information about your visit, automatically, while, at the same time, it does not identify you personally. We do automatically collect and store information about your visit, e.g.: Internet Protocol (IP) your computer (which is a number that is assigned automatically to your computer at any time you browse the Internet), used web browser and operating systems, which websites you moved from to our Website, date and time of your access to our website, and pages visited. We use this information to help us make our Site more useful to visitors, to find out the number of visitors to our Site, and the type of technology used by our visitors. We do not track down or record any information that relate to the individuals and to their visits.":
    "عزيزي المستخدم، عند تصفحك موقع شرطة دبي نقوم تلقائيًا بجمع وتخزين معلومات معينة عن زيارتك دون أن تحدد هويتك الشخصية. ومن هذه المعلومات: عنوان بروتوكول الإنترنت (IP) لجهازك (وهو رقم يُخصَّص تلقائيًا لجهازك عند تصفح الإنترنت)، ومتصفح الويب ونظام التشغيل المستخدمان، والمواقع التي انتقلت منها إلى موقعنا، وتاريخ ووقت دخولك إلى الموقع، والصفحات التي زرتها. ونستخدم هذه المعلومات لجعل موقعنا أكثر فائدة للزوار، ولمعرفة عدد زوار الموقع ونوع التقنية التي يستخدمونها. ولا نتتبع أو نسجل أي معلومات تتعلق بالأفراد وزياراتهم.",
  "Dubai Police Site uses cookies to follow the users while browsing only to collect and analyze usage statistics for development and improvement and providing users with the best experience of our Site. Use of cookies is usual practice in the electronic websites. Cookies are simple text files stored in your personal computer by the web browser. It provides a distinction tool between site visitors. Cookies do not contain any personal identification number (PIN) or subject your privacy or information to any risk. It is possible to set most web browsers to reject cookies, accept, or delete these files. However, the refusal or removing cookies may obstruct those to run complete and faster.":
    "يستخدم موقع شرطة دبي ملفات تعريف الارتباط لتتبع المستخدمين أثناء التصفح فقط بهدف جمع إحصاءات الاستخدام وتحليلها للتطوير والتحسين وتقديم أفضل تجربة للمستخدمين. واستخدام هذه الملفات ممارسة معتادة في المواقع الإلكترونية، وهي ملفات نصية بسيطة يخزنها متصفح الويب في جهازك، وتوفر وسيلة للتمييز بين زوار الموقع. ولا تحتوي على أي رقم تعريف شخصي ولا تعرّض خصوصيتك أو معلوماتك لأي خطر. ويمكن ضبط معظم المتصفحات لرفض هذه الملفات أو قبولها أو حذفها، غير أن رفضها أو إزالتها قد يعيق تشغيل الموقع بشكل كامل وأسرع.",
  "For an effective and efficient service, Dubai Police collects some specific data of users, in certain places within the Site. Dubai Police is committed to maintain the confidentiality of all the information collected from users and will not allow accessing them but to the authorized government officials and within the limits of what they need to know only. Dubai Police needs the data that enable it to understand the needs of users and provide them with the correct service, accurately and completely. Hence, you must ensure that the information are complete and accurate and that you will not attempt to use the Site using someone else’s name. we will not provide any information you give us to any private organizations or persons, from the private sector. Dubai Police does not collect or use information for commercial marketing.":
    "لتقديم خدمة فعّالة وكفؤة، تجمع شرطة دبي بعض البيانات المحددة من المستخدمين في مواضع معينة داخل الموقع. وتلتزم شرطة دبي بالحفاظ على سرية جميع المعلومات المجمّعة من المستخدمين، ولن تسمح بالاطلاع عليها إلا للموظفين الحكوميين المخوّلين وفي حدود ما يحتاجون إلى معرفته فقط. وتحتاج شرطة دبي إلى البيانات التي تمكّنها من فهم احتياجات المستخدمين وتقديم الخدمة الصحيحة لهم بدقة واكتمال. لذا يجب عليك التأكد من اكتمال المعلومات وصحتها وعدم محاولة استخدام الموقع باسم شخص آخر. ولن نقدم أي معلومات تزودنا بها إلى أي مؤسسات أو أشخاص من القطاع الخاص. ولا تجمع شرطة دبي المعلومات أو تستخدمها لأغراض التسويق التجاري.",
  "We will not collect any personal information, when you visit our Website, except when you provide it, voluntarily, through your participation in activities that require information (such as: reporting a crime, providing confidential information, sending email, participating in an inspection report, logging in to electronic services; such as the link for paying traffic fines, etc.). In some cases, the information we collect would be transferred to police agencies and other government departments to deal with the purpose stated by the user.":
    "لن نجمع أي معلومات شخصية عند زيارتك لموقعنا إلا إذا قدمتها طوعًا من خلال مشاركتك في أنشطة تتطلب معلومات (مثل: الإبلاغ عن جريمة، أو تقديم معلومات سرية، أو إرسال بريد إلكتروني، أو المشاركة في تقرير تفتيش، أو تسجيل الدخول إلى الخدمات الإلكترونية كرابط دفع المخالفات المرورية). وفي بعض الحالات تُنقل المعلومات التي نجمعها إلى الجهات الشرطية والدوائر الحكومية الأخرى لمعالجة الغرض الذي ذكره المستخدم.",
  "When you visit certain parts of this Site, you may be asked to provide personal information to make sure of your identity (such as name, address, sex, and perhaps credit card number), all of which are necessary to complete your transaction information. However, the card number will not be stored, under any circumstances. However, if you refuse to provide such information, you limit our ability to serve you. However, in any case, we continue to invite you to visit our Site and take advantage of the valuable information we offer.":
    "عند زيارتك لأجزاء معينة من هذا الموقع قد يُطلب منك تقديم معلومات شخصية للتحقق من هويتك (مثل الاسم والعنوان والجنس وربما رقم بطاقة الائتمان)، وجميعها ضرورية لاستكمال بيانات معاملتك. ولن يُخزَّن رقم البطاقة تحت أي ظرف. وإذا رفضت تقديم هذه المعلومات فإنك تحدّ من قدرتنا على خدمتك، ومع ذلك تبقى دعوتنا قائمة لزيارة موقعنا والاستفادة من المعلومات القيّمة التي نقدمها.",
  "This Site takes all the necessary precautions to protect users information. When users submit sensitive information via the Website, all are protected, whether when in use or after they were used. While encryption is used to protect sensitive information when in use, we do everything in our power to protect all information in the case of non-use. All electronic transactions performed by users, with Dubai Police, are subjected to the use of Secure Sockets Layer technology (SSL).":
    "يتخذ هذا الموقع جميع الاحتياطات اللازمة لحماية معلومات المستخدمين. وعند إرسال المستخدمين معلومات حساسة عبر الموقع فإنها تُحمى سواء أثناء الاستخدام أو بعده. ويُستخدم التشفير لحماية المعلومات الحساسة أثناء الاستخدام، ونبذل كل ما في وسعنا لحماية جميع المعلومات في حالة عدم الاستخدام. وتخضع جميع المعاملات الإلكترونية التي ينفذها المستخدمون مع شرطة دبي لتقنية طبقة المقابس الآمنة (SSL).",
  "Dubai Police Site is protected by multiple security measures, such as documentation, monitoring, auditing, and encryption. Dubai Police uses a variety of other mechanisms, security measurements; and technical, regulatory, and reasonable precautions; in the design and implementation of the daily operations. We continue our engagement with the electronic content and the electronic transfer of information to make sure that the data provided by users are not misused or modified or lost. These measurements include control, regular storage backup, and applying of database security policies.":
    "موقع شرطة دبي محمي بإجراءات أمنية متعددة كالتوثيق والمراقبة والتدقيق والتشفير. وتستخدم شرطة دبي مجموعة من الآليات والتدابير الأمنية والاحتياطات الفنية والتنظيمية المعقولة في تصميم العمليات اليومية وتنفيذها. ونواصل متابعة المحتوى الإلكتروني والنقل الإلكتروني للمعلومات للتأكد من عدم إساءة استخدام البيانات التي يقدمها المستخدمون أو تعديلها أو فقدانها. وتشمل هذه التدابير الرقابة والنسخ الاحتياطي الدوري وتطبيق سياسات أمن قواعد البيانات.",
  "Dubai Police and would like to draw the attention of users to the fact that the data sent over the Internet is unsecured in nature, and therefore Dubai Police does not guarantee that data sent over the Internet are secured. Users are responsible for maintaining the confidentiality of their own users’ names and passwords. Dubai Police will not request any personal password unless user would like to use it to access a service or secured pages.":
    "تلفت شرطة دبي انتباه المستخدمين إلى أن البيانات المرسلة عبر الإنترنت غير مؤمّنة بطبيعتها، ومن ثمّ فإن شرطة دبي لا تضمن أمان البيانات المرسلة عبر الإنترنت. ويتحمل المستخدمون مسؤولية الحفاظ على سرية أسماء المستخدمين وكلمات المرور الخاصة بهم. ولن تطلب شرطة دبي أي كلمة مرور شخصية إلا إذا رغب المستخدم في استخدامها للوصول إلى خدمة أو صفحات مؤمّنة.",
  "Dubai Police Website contains links to other websites that are provided only as service information and they are subject to their own privacy policy. Dubai Police is not responsible for any content available at these sites. Therefore, we advise you to have access to the privacy policies of those websites, which you visited through Dubai Police Website to determine the site-based practices there.":
    "يحتوي موقع شرطة دبي على روابط لمواقع أخرى تُقدَّم كمعلومات خدمية فقط وتخضع لسياسات الخصوصية الخاصة بها. ولا تتحمل شرطة دبي مسؤولية أي محتوى متاح في تلك المواقع، لذا ننصحك بالاطلاع على سياسات الخصوصية الخاصة بالمواقع التي تزورها عبر موقع شرطة دبي لمعرفة الممارسات المتبعة فيها.",
  "Users should note that Dubai Police does not promote these sites neither it is sure of the contents or the products and services they offer. Dubai Police shall not exercise any authority whatsoever over the sites that are not owned or managed by it. Dubai Police is not responsible for protecting any information/data that the user provide when visiting those sites, including information security and privacy practices of these sites.":
    "على المستخدمين ملاحظة أن شرطة دبي لا تروّج لهذه المواقع ولا تضمن محتوياتها أو ما تقدمه من منتجات وخدمات، ولا تمارس أي سلطة على المواقع التي لا تملكها أو تديرها. ولا تتحمل شرطة دبي مسؤولية حماية أي معلومات أو بيانات يقدمها المستخدم عند زيارة تلك المواقع، بما في ذلك ممارسات أمن المعلومات والخصوصية فيها.",
  "In case you want to close your account or in the event that someone has stolen your account, you can report that to our Call Center (901), around the clock, or communicate your concern via email: mail@dubaipolice.gov.ae. Your account will be closed after confirming your identity but the personal information of the account will remain in our database to deter fraud by ensuring that persons who try to commit fraud will not be able to escape detection attempt, by closing their accounts and opening new accounts. However, if you close your account, we will not use your personal information for any other purpose, and will not sell or share any with third parties, unless the law requires it.":
    "إذا رغبت في إغلاق حسابك أو في حال قام شخص بسرقة حسابك، يمكنك إبلاغ مركز الاتصال (901) على مدار الساعة أو مراسلتنا عبر البريد الإلكتروني: mail@dubaipolice.gov.ae. وسيُغلق حسابك بعد التحقق من هويتك، غير أن المعلومات الشخصية للحساب تبقى في قاعدة بياناتنا للحد من الاحتيال وضمان ألا يتمكن من يحاول الاحتيال من الإفلات من الكشف بإغلاق حسابه وفتح حساب جديد. ومع ذلك، إذا أغلقت حسابك فلن نستخدم معلوماتك الشخصية لأي غرض آخر ولن نبيعها أو نشاركها مع أي طرف ثالث ما لم يقتضِ القانون ذلك.",
  "Government Records and Retention: Service applications, requests, supporting documents, and related records submitted through the application form part of official government archives. In compliance with applicable UAE laws and government record-retention regulations, these official records cannot be deleted upon individual request.":
    "السجلات الحكومية والاحتفاظ بها: تشكّل طلبات الخدمة والمستندات المؤيدة والسجلات ذات الصلة المقدَّمة عبر التطبيق جزءًا من الأرشيف الحكومي الرسمي. والتزامًا بقوانين دولة الإمارات وأنظمة الاحتفاظ بالسجلات الحكومية، لا يمكن حذف هذه السجلات الرسمية بناءً على طلب فردي.",
  "The Dubai Police mobile application does not create, manage, or store local user profiles. Authentication is securely handled via UAE PASS, an independent national digital identity service. Dubai Police does not control UAE PASS accounts or the personal data managed within that ecosystem. Personal information received through UAE PASS is used strictly to verify your identity and process the official government services you request.":
    "لا ينشئ تطبيق شرطة دبي ملفات مستخدمين محلية ولا يديرها أو يخزّنها. وتتم عملية المصادقة بصورة آمنة عبر الهوية الرقمية UAE PASS، وهي خدمة هوية رقمية وطنية مستقلة. ولا تتحكم شرطة دبي في حسابات UAE PASS ولا في البيانات الشخصية المُدارة ضمن تلك المنظومة. وتُستخدم المعلومات الشخصية الواردة عبر UAE PASS حصريًا للتحقق من هويتك ومعالجة الخدمات الحكومية الرسمية التي تطلبها.",
  "Managing Your Data & Contact Us: If you wish to manage your digital identity or profile data, please contact UAE PASS directly. For any questions regarding how Dubai Police processes your service requests or to exercise your rights under applicable data protection laws, please reach out to us at mail@dubaipolice.gov.ae":
    "إدارة بياناتك والتواصل معنا: إذا رغبت في إدارة هويتك الرقمية أو بيانات ملفك الشخصي، يُرجى التواصل مع UAE PASS مباشرة. ولأي استفسار حول كيفية معالجة شرطة دبي لطلبات الخدمة الخاصة بك أو لممارسة حقوقك بموجب قوانين حماية البيانات المعمول بها، يُرجى مراسلتنا على mail@dubaipolice.gov.ae",
  "Dubai Police’s app collects location data to enable features like Report Accident, Drive mode, Police Eye, My Map and Sail Safely. Our Sale Safely feature also requires Background Location Permission for the better use of the feature.":
    "يجمع تطبيق شرطة دبي بيانات الموقع لتفعيل خصائص مثل الإبلاغ عن حادث، ووضع القيادة، وعين الشرطة، وخريطتي، وأبحر بأمان. وتتطلب خاصية «أبحر بأمان» أيضًا إذن الموقع في الخلفية للاستفادة منها بشكل أفضل.",
  "We use this information to provide the requested location-based Service, not to identify you but to:":
    "نستخدم هذه المعلومات لتقديم الخدمة المعتمدة على الموقع التي طلبتها، لا لتحديد هويتك وإنما لـ:",
  "Provide you accurate service access based upon your location.":
    "منحك وصولًا دقيقًا إلى الخدمة بناءً على موقعك.",
  "Provide you some important information like nearby Police Stations and more.":
    "تزويدك ببعض المعلومات المهمة مثل مراكز الشرطة القريبة وغيرها.",
  "Dubai Police may make some adjustments in the Privacy Policy to accommodate changes in the legal and regulatory requirements, business requirement for upgrading technologies and applications, or for service improvement. Dubai Police reserves the right to make any radical or slight modification of the content of this document at any time and without prior notice. Continue to use the Site means your acceptance of such changes. Please review this Policy periodically. In case of radical changes in this Policy, we will inform you via email or by means of a notice in our Homepage.":
    "قد تُجري شرطة دبي بعض التعديلات على سياسة الخصوصية لمواكبة التغيرات في المتطلبات القانونية والتنظيمية، أو متطلبات العمل لتحديث التقنيات والتطبيقات، أو لتحسين الخدمة. وتحتفظ شرطة دبي بحقها في إجراء أي تعديل جوهري أو طفيف على محتوى هذه الوثيقة في أي وقت ودون إشعار مسبق. ويعني استمرارك في استخدام الموقع قبولك لهذه التغييرات. يُرجى مراجعة هذه السياسة دوريًا. وفي حال إجراء تغييرات جوهرية سنُعلمك عبر البريد الإلكتروني أو بإشعار في صفحتنا الرئيسية.",
  "If you have any questions or suggestions regarding our privacy policy, please contact us at ":
    "إذا كان لديك أي استفسار أو اقتراح بشأن سياسة الخصوصية، يُرجى التواصل معنا على ",

  // --- terms and conditions ------------------------------------------------
  "Copyright ©2020 Dubai Police, All Rights Reserved. Any rights not expressly granted herein are reserved. No copyrighted material may be distributed, downloaded, modified, reused, copied, reproduced, transferred, displayed, reposted, transmitted, disseminated, sold, published, broadcast or circulated or otherwise used except as expressly stated either in such materials or in this notice without the express written permission of Dubai Police.":
    "حقوق النشر ©2020 شرطة دبي، جميع الحقوق محفوظة. وأي حقوق لم تُمنح صراحةً هنا فهي محفوظة. ولا يجوز توزيع أي مادة محمية بحقوق النشر أو تنزيلها أو تعديلها أو إعادة استخدامها أو نسخها أو إعادة إنتاجها أو نقلها أو عرضها أو إعادة نشرها أو بثها أو نشرها أو بيعها أو تداولها أو استخدامها بأي صورة أخرى إلا وفق ما هو منصوص عليه صراحةً في تلك المواد أو في هذا الإشعار ودون إذن كتابي صريح من شرطة دبي.",
  "The marks or logos appearing through this web site are proprietary of Dubai Police. You are prohibited from using any of the marks or logos without permission from Dubai Police, except as permitted by applicable law.":
    "العلامات والشعارات الظاهرة في هذا الموقع مملوكة لشرطة دبي، ويُحظر استخدام أي منها دون إذن من شرطة دبي إلا في الحدود التي يجيزها القانون المعمول به.",
  "Dubai Police web site and material relating to Police information, products and services (or to third party information, products and services) is provided as is without any representation or endorsement made and without warranty of any kind, whether express or implied, including but not limited to the implied warranties of satisfactory quality, fitness for a particular purpose non-infringement, compatibility security and accuracy. The information on this site is provided for convenience as part of the service we offer at this website.":
    "يُقدَّم موقع شرطة دبي والمواد المتعلقة بمعلومات الشرطة ومنتجاتها وخدماتها (أو بمعلومات ومنتجات وخدمات الغير) «كما هي» دون أي إقرار أو تأييد ودون أي ضمان من أي نوع، صريح أو ضمني، بما في ذلك على سبيل المثال لا الحصر الضمانات الضمنية المتعلقة بالجودة المُرضية والملاءمة لغرض معين وعدم المخالفة والتوافق والأمن والدقة. وتُقدَّم المعلومات في هذا الموقع لأغراض التيسير كجزء من الخدمة التي نوفرها.",
  "Dubai Police web site and material relating to Police information, products and services (or to third party information, products and services) is provided as is without any representation or endorsement made and without warranty of any kind, whether express or implied, including but not limited to the implied warranties of satisfactory quality, fitness for a particular purpose non-infringement, compatibility, security and accuracy. The information on this site is provided for convince as part of the service we offer at this website.":
    "يُقدَّم موقع شرطة دبي والمواد المتعلقة بمعلومات الشرطة ومنتجاتها وخدماتها (أو بمعلومات ومنتجات وخدمات الغير) «كما هي» دون أي إقرار أو تأييد ودون أي ضمان من أي نوع، صريح أو ضمني، بما في ذلك على سبيل المثال لا الحصر الضمانات الضمنية المتعلقة بالجودة المُرضية والملاءمة لغرض معين وعدم المخالفة والتوافق والأمن والدقة. وتُقدَّم المعلومات في هذا الموقع لأغراض التيسير كجزء من الخدمة التي نوفرها.",
  "In no event will Dubai Police be liable for any damages whatsoever, but not limited to any direct, incidental, consequential, special, exemplary or other indirect damages arising out of the use of or inability to use the site, the services or the content; any transaction conducted through or facilitated by the site; any claim attributable to errors, omissions, or other inaccuracies in the site.":
    "لن تكون شرطة دبي في أي حال مسؤولة عن أي أضرار أيًا كانت، بما في ذلك على سبيل المثال لا الحصر الأضرار المباشرة أو العرضية أو التبعية أو الخاصة أو التأديبية أو غير المباشرة الناشئة عن استخدام الموقع أو الخدمات أو المحتوى أو عن تعذر استخدامها، أو عن أي معاملة تُجرى عبر الموقع أو بتيسير منه، أو عن أي مطالبة تُعزى إلى أخطاء أو إغفالات أو عدم دقة في الموقع.",
  "The service and/or content, unauthorized access to or alteration of your transmissions or data or any other matter relating to the site, the service or the content even if Dubai Police has been advised of the possibility of such damages or losses. If you are dissatisfied with the site, the content, or with the terms of use, your sole and exclusive remedy is to discontinue using the site.":
    "أو عن الخدمة و/أو المحتوى، أو الوصول غير المصرح به إلى إرسالاتك أو بياناتك أو تغييرها، أو أي أمر آخر يتعلق بالموقع أو الخدمة أو المحتوى، حتى لو أُبلغت شرطة دبي بإمكانية حدوث هذه الأضرار أو الخسائر. وإذا لم تكن راضيًا عن الموقع أو المحتوى أو شروط الاستخدام، فإن سبيل الانتصاف الوحيد والحصري المتاح لك هو التوقف عن استخدام الموقع.",
  "As a condition of your use of Dubai Police Web site, you warrant to Dubai Police that you will not use Dubai Police Web site for any purpose that is unlawful or that is prohibited by these terms of use and notices. You may not use Dubai Police Web site in any manner which could damage, disable, overburden, or impair the Web site and servers. You may not use Dubai Police Web site or servers to publish, post, distribute or disseminate any defamatory, obscene or otherwise unlawful material or information, including another's proprietary information, including trademarks or copyrighted information, without express authorization from the rights holder.":
    "كشرط لاستخدامك موقع شرطة دبي، تتعهد لشرطة دبي بعدم استخدام الموقع لأي غرض غير مشروع أو محظور بموجب شروط الاستخدام والإشعارات هذه. ولا يجوز لك استخدام الموقع بأي صورة قد تُلحق الضرر بالموقع أو الخوادم أو تعطّلها أو تحمّلها فوق طاقتها أو تضعف أداءها. ولا يجوز استخدام موقع شرطة دبي أو خوادمه لنشر أو بث أو توزيع أي مواد أو معلومات تشهيرية أو فاحشة أو غير مشروعة، بما في ذلك معلومات مملوكة للغير كالعلامات التجارية أو المواد المحمية بحقوق النشر، دون إذن صريح من صاحب الحق.",
  "The information, materials, software, products and services (collectivity data) included in or available through Dubai Police web site and services may be superseded and/or may include inaccuracies or typographical errors. Changes are periodically made to the date contained herein.":
    "قد تُستبدل المعلومات والمواد والبرمجيات والمنتجات والخدمات (ويُشار إليها مجتمعةً بـ«البيانات») المتضمنة في موقع شرطة دبي وخدماته أو المتاحة من خلاله، وقد تتضمن أخطاءً أو عدم دقة أو أخطاءً مطبعية. وتُجرى تغييرات دورية على البيانات الواردة فيه.",
  "Dubai Police may amend or modify this agreement or impose new conditions at any time. Any use of the Web site by you after such notice shall be deemed to constitute acceptance by you of such amendments, modifications or new conditions. You are responsible for regularly reviewing these terms, conditions and notices.":
    "يجوز لشرطة دبي تعديل هذه الاتفاقية أو فرض شروط جديدة في أي وقت. ويُعدّ أي استخدام للموقع من جانبك بعد هذا الإشعار قبولًا منك لتلك التعديلات أو الشروط الجديدة. وتقع عليك مسؤولية مراجعة هذه الشروط والأحكام والإشعارات بصورة منتظمة.",
  "This Agreement is entered into in the Emirate of United Arab Emirates and shall be governed by and constructed in accordance with the laws of the United Arab Emirates.":
    "أُبرمت هذه الاتفاقية في دولة الإمارات العربية المتحدة، وتخضع لقوانين دولة الإمارات العربية المتحدة وتُفسَّر وفقًا لها.",
  "Links on this Web Site to third party web sites or information are provided solely as a convenience to you. We will make every effort to clearly indicate that you are leaving Dubai Police web site to go to a linked site but by definition links on Dubai Police web site will lead to other web sites which are not under our control and you are subject to the terms of use and privacy policy applicable to those web sites. We are not responsible for the content of any linked site. We cannot guarantee that these links will work all of the time and have no control over the availability of the linked pages. Visitors who rely on this information do so at their own risk.":
    "تُقدَّم الروابط الموجودة في هذا الموقع إلى مواقع أو معلومات تابعة للغير لغرض التيسير عليك فقط. وسنبذل كل جهد لتوضيح أنك تغادر موقع شرطة دبي إلى موقع مرتبط، غير أن هذه الروابط تؤدي بطبيعتها إلى مواقع أخرى ليست تحت سيطرتنا وتخضع لشروط الاستخدام وسياسات الخصوصية الخاصة بها. ولا نتحمل مسؤولية محتوى أي موقع مرتبط، ولا يمكننا ضمان عمل هذه الروابط في كل وقت، ولا سيطرة لنا على توافر الصفحات المرتبطة. ومن يعتمد على هذه المعلومات يفعل ذلك على مسؤوليته.",
  "If you are registered with Dubai Police Web Site for accessing online services, you are responsible for maintaining the confidentiality of your member identification and password information and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your member identification and password.":
    "إذا كنت مسجلًا في موقع شرطة دبي للوصول إلى الخدمات الإلكترونية، فأنت مسؤول عن الحفاظ على سرية معرّف العضوية وكلمة المرور الخاصين بك وعن تقييد الوصول إلى جهازك. وتوافق على تحمل المسؤولية عن جميع الأنشطة التي تتم باستخدام معرّف العضوية وكلمة المرور الخاصين بك.",
  "Dubai Police Web site, servers and computer system may be monitored for all lawful purposes, including to ensure that their use is authorized, to manage the Web site, server and computer system, to facilitate protection against unauthorized access, and to verify security procedures, survivability and operational security. All information (including without limitation, personal information and electronic communications) placed on or sent over this Web site, server or computer system may be monitored by Dubai Police. The unauthorized use of the Web site, server or computer system may subject you to criminal prosecution. Please read the Dubai Police Web Site Privacy Policy that addresses other privacy issues associated with Dubai Police Website.":
    "قد تخضع مواقع شرطة دبي وخوادمها وأنظمتها الحاسوبية للمراقبة لجميع الأغراض المشروعة، بما في ذلك التأكد من أن استخدامها مصرّح به، وإدارة الموقع والخادم والنظام الحاسوبي، وتيسير الحماية من الوصول غير المصرح به، والتحقق من الإجراءات الأمنية وقابلية الاستمرار والأمن التشغيلي. وقد تراقب شرطة دبي جميع المعلومات (بما في ذلك على سبيل المثال لا الحصر المعلومات الشخصية والاتصالات الإلكترونية) الموضوعة على هذا الموقع أو الخادم أو النظام الحاسوبي أو المرسلة عبرها. وقد يعرّضك الاستخدام غير المصرح به للموقع أو الخادم أو النظام الحاسوبي للملاحقة الجزائية. يُرجى قراءة سياسة الخصوصية الخاصة بموقع شرطة دبي التي تتناول مسائل الخصوصية الأخرى المرتبطة بالموقع.",
  "We make every effort to check and test material at all stages of production. It is always wise for you to run an anti-virus program on all material downloaded from the internet. We cannot accept any responsibility for any loss, disruption or damage to your data or your computer system which may occur whilst using material derived from this website.":
    "نبذل كل جهد لفحص المواد واختبارها في جميع مراحل الإنتاج. ومن الحكمة دائمًا تشغيل برنامج مضاد للفيروسات على جميع المواد التي تُنزَّل من الإنترنت. ولا يمكننا تحمل أي مسؤولية عن أي فقد أو تعطل أو ضرر يلحق ببياناتك أو بنظامك الحاسوبي أثناء استخدام مواد مستمدة من هذا الموقع.",
  'To make sure you get "Dubai Police" services that require electronic payment, legally and safely, avoid payment through an intermediary or by using a credit card or direct debit and/or using other means of payment that belong to third parties, without their consent.':
    "لضمان حصولك على خدمات «شرطة دبي» التي تتطلب الدفع الإلكتروني بصورة قانونية وآمنة، تجنّب الدفع عبر وسيط أو باستخدام بطاقة ائتمان أو خصم مباشر و/أو وسائل دفع أخرى تخص الغير دون موافقتهم.",
  "In case of violation of the above and/or complaint from the rightful owner of the means of electronic payment used, the client (whether natural or legal person) is subject to legal accountability and is punished by imprisonment and payment of fine, or by either, in accordance with Articles 11, 12, 13 and 14 of the Decree of Federal Law (5/2012), related to combating cybercrimes, without prejudice to the right of Dubai Police in exercising all means of legal protection and rights available and/or granted to it under the law.":
    "في حال مخالفة ما سبق و/أو ورود شكوى من المالك الشرعي لوسيلة الدفع الإلكتروني المستخدمة، يخضع المتعامل (شخصًا طبيعيًا كان أم اعتباريًا) للمساءلة القانونية ويُعاقب بالحبس والغرامة أو بإحداهما وفقًا للمواد 11 و12 و13 و14 من المرسوم بقانون اتحادي رقم (5/2012) في شأن مكافحة جرائم تقنية المعلومات، دون الإخلال بحق شرطة دبي في ممارسة جميع وسائل الحماية القانونية والحقوق المتاحة أو الممنوحة لها بموجب القانون.",

  // --- customer service agreement -----------------------------------------
  "An entity pledged to make customers happy": "جهة تتعهد بإسعاد المتعاملين",
  "An Employee Proud to deliver distinguished service":
    "موظف يفخر بتقديم خدمة متميزة",
  "Positive and proactive customer": "متعامل إيجابي ومبادر",
  "Provide distinguished and high quality service":
    "تقديم خدمة متميزة وعالية الجودة",
  "Provide qualified and highly trained employees":
    "توفير موظفين مؤهلين وعلى درجة عالية من التدريب",
  "Provide Smart, Digital and E Services on a 24 hour basis":
    "توفير الخدمات الذكية والرقمية والإلكترونية على مدار 24 ساعة",
  "Provide transparency": "توفير الشفافية",
  "Provide Service Completion requirements and completion details":
    "توضيح متطلبات إنجاز الخدمة وتفاصيل الإنجاز",
  "Simplify procedures to enhance the quality of customer s journey":
    "تبسيط الإجراءات لتعزيز جودة رحلة المتعامل",
  "Accept opinions, receive and handle complaints and remarks.":
    "تقبّل الآراء واستقبال الشكاوى والملاحظات ومعالجتها.",
  "Appreciate employee s efforts": "تقدير جهود الموظفين",
  "Greet you and offer attentive and unbiased service.":
    "الترحيب بك وتقديم خدمة متيقظة ومحايدة.",
  "Understand your needs, assist and advice you for an effective problem solving and service delivery":
    "فهم احتياجاتك ومساعدتك وإرشادك لحل المشكلات وتقديم الخدمة بفعالية",
  "Serve your needs adequately and professionally":
    "تلبية احتياجاتك بالشكل المناسب وباحترافية",
  "Efficient and humane treatment especially of victims of offences":
    "معاملة كفؤة وإنسانية، خاصة لضحايا الجرائم",
  "Give priority to serious cases, to the People of Determination and to the elderly":
    "إعطاء الأولوية للحالات الطارئة ولأصحاب الهمم وكبار المواطنين",
  "Abide by the law": "الالتزام بالقانون",
  "Provide required documents": "تقديم المستندات المطلوبة",
  "Provide your up to date information on our database":
    "تحديث بياناتك في قاعدة بياناتنا",
  "Respond to our inquiries": "الاستجابة لاستفساراتنا",
  "Offer constructive feedback and suggestions":
    "تقديم ملاحظات واقتراحات بنّاءة",
  "Understand our priority system": "تفهّم نظام الأولويات لدينا",
  "Community Activities Participation": "المشاركة في الأنشطة المجتمعية",
  "Call 999 only in case of emergency": "اتصل بالرقم 999 في حالات الطوارئ فقط",
};
