/**
 * Generated by scripts/gen-footer-content.mjs from the site's own APIs.
 * Edit the generator, not this file.
 */

export const privacyPolicy = {
  title: "Privacy Policy",
  sections: [
    {
      title: "Overview",
      content: [
        {
          link: {
            href: "https://fct.npf.gov.ng",
            label: "fct.npf.gov.ng",
          },
          text: 'The Nigeria Police Force is committed to protecting the rights of visitors to its Website and to maintaining the confidentiality of personal information that is used in this Website. Privacy Policy aims to clarify the approach of the Nigeria Police Force, and the obligations; with respect to the collection, use, distribution, retention, destruction and dissemination (collectively called, "use" or "usage" or their derivatives) of personal information or data (collectively called, "data") which is collected on The Nigeria Police Force eServices Website at ',
          type: "paragraph",
          afterText: ".",
        },
      ],
    },
    {
      title: "Policy Statement",
      content: [
        {
          text: "The information that Nigeria Police Force may obtain from users of this website on the internet is treated with utmost privacy and confidentiality, and it is not disclosed to third parties except for legal, security, or awareness purposes.",
          type: "paragraph",
        },
        {
          text: "We will not collect any personal information, when you visit our Website, except when you provide it, voluntarily, through your participation in activities that require information (such as: reporting a crime, providing confidential information, sending email, participating in an inspection report, logging in to electronic services; such as the link for paying traffic fines, etc.). In some cases, the information we collect would be transferred to police agencies and other government departments to deal with the purpose stated by the user.",
          type: "paragraph",
        },
        {
          text: "Any data required from the user, in this Website, will be used, exclusively, in accordance with the privacy policy set forth below. Nigeria Police Force will never ask for any unnecessary data.",
          type: "paragraph",
        },
        {
          text: 'Nigeria Police Force Website includes public pages that can be browsed by all users, without having to provide any personal data with the exception of data collected by cookies when used (see details below). The Site also contains secured pages that require registration to be accessed, using the form "request a user registration", in the open public pages.',
          type: "paragraph",
        },
      ],
    },
    {
      title: "Policy Scope",
      content: [
        {
          text: "Privacy Policy, set forth in this document, applies to Nigeria Police Force Website (fct.npf.gov.ng) and to the information collected by this Site only. This Policy also applies to all employees of Nigeria Police Force, apart from their place of work, and also to all the concerned suppliers’ employees, irrespective of the place of whoever manages Nigeria Police Force Website, which can obtain personal data of the users.",
          type: "paragraph",
        },
        {
          text: "Nigeria Police Force Website contains links to other websites that are provided only as service information and they are subject to their own privacy policy. Nigeria Police Force is not responsible for any content available at these sites. Therefore, we advise you to have access to the privacy policies of those websites, which you visited through Nigeria Police Force Website to determine the site-based practices there.",
          type: "paragraph",
        },
        {
          text: "Users should note that Nigeria Police Force does not promote these sites neither it is sure of the contents or the products and services they offer. Nigeria Police Force shall not exercise any authority whatsoever over the sites that are not owned or managed by it. Nigeria Police Force is not responsible for protecting any information/data that the user provide when visiting those sites, including information security and privacy practices of these sites.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Collection and Storage of Information Automatically",
      content: [
        {
          text: "Dear user, when browsing Nigeria Police Force Website, we will collect and store certain information about your visit, automatically, while, at the same time, it does not identify you personally. We do automatically collect and store information about your visit, e.g.: Internet Protocol (IP) your computer (which is a number that is assigned automatically to your computer at any time you browse the Internet), used web browser and operating systems, which websites you moved from to our Website, date and time of your access to our website, and pages visited. We use this information to help us make our Site more useful to visitors, to find out the number of visitors to our Site, and the type of technology used by our visitors. We do not track down or record any information that relate to the individuals and to their visits.",
          type: "paragraph",
        },
        {
          text: "When you visit certain parts of this Site, you may be asked to provide personal information to make sure of your identity (such as name, address, sex, and perhaps credit card number), all of which are necessary to complete your transaction information. However, the card number will not be stored, under any circumstances. However, if you refuse to provide such information, you limit our ability to serve you. However, in any case, we continue to invite you to visit our Site and take advantage of the valuable information we offer.",
          type: "paragraph",
        },
        {
          text: "Nigeria Police Force Site uses cookies to follow the users while browsing only to collect and analyze usage statistics for development and improvement and providing users with the best experience of our Site. Use of cookies is usual practice in the electronic websites. Cookies are simple text files stored in your personal computer by the web browser. It provides a distinction tool between site visitors. Cookies do not contain any personal identification number (PIN) or subject your privacy or information to any risk. It is possible to set most web browsers to reject cookies, accept, or delete these files. However, the refusal or removing cookies may obstruct those to run complete and faster.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Protection of personal information",
      content: [
        {
          text: "For an effective and efficient service, Nigeria Police Force collects some specific data of users, in certain places within the Site. Nigeria Police Force is committed to maintain the confidentiality of all the information collected from users and will not allow accessing them but to the authorized government officials and within the limits of what they need to know only. Nigeria Police Force needs the data that enable it to understand the needs of users and provide them with the correct service, accurately and completely. Hence, you must ensure that the information are complete and accurate and that you will not attempt to use the Site using someone else’s name. we will not provide any information you give us to any private organizations or persons, from the private sector. Nigeria Police Force does not collect or use information for commercial marketing.",
          type: "paragraph",
        },
        {
          text: "Dear user, if you wish to provide us with information about you by sending an email or fill the form for your personal information and submit it to us, via our Website, we use these information to respond to your message and to help us provide you with the information you requested. If you send your data summary across our Website, we use your personal data for employment purpose only and not for other purposes.",
          type: "paragraph",
        },
        {
          text: "Nigeria Police Force Website encompasses a range of services and transactions that allow you to pay transaction fees electronically by entering credit card data in Nigeria Police Force Payment Screen where credit card data are not stored in our databases, to ensure that the credit card is not used, by anyone else.",
          type: "paragraph",
        },
        {
          text: "In case you want to close your account or in the event that someone has stolen your account, you can report that to our Complaint Response Unit (0805 700 0001), around the clock, or communicate your concern via email: mail@npf.gov.ng. Your account will be closed after confirming your identity but the personal information of the account will remain in our database to deter fraud by ensuring that persons who try to commit fraud will not be able to escape detection attempt, by closing their accounts and opening new accounts. However, if you close your account, we will not use your personal information for any other purpose, and will not sell or share any with third parties, unless the law requires it.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Information Security",
      content: [
        {
          text: "Nigeria Police Force Site is protected by multiple security measures, such as documentation, monitoring, auditing, and encryption. Nigeria Police Force uses a variety of other mechanisms, security measurements; and technical, regulatory, and reasonable precautions; in the design and implementation of the daily operations. We continue our engagement with the electronic content and the electronic transfer of information to make sure that the data provided by users are not misused or modified or lost. These measurements include control, regular storage backup, and applying of database security policies.",
          type: "paragraph",
        },
        {
          text: "This Site takes all the necessary precautions to protect users information. When users submit sensitive information via the Website, all are protected, whether when in use or after they were used. While encryption is used to protect sensitive information when in use, we do everything in our power to protect all information in the case of non-use. All electronic transactions performed by users, with Nigeria Police Force, are subjected to the use of Secure Sockets Layer technology (SSL).",
          type: "paragraph",
        },
        {
          text: "Nigeria Police Force and would like to draw the attention of users to the fact that the data sent over the Internet is unsecured in nature, and therefore Nigeria Police Force does not guarantee that data sent over the Internet are secured. Users are responsible for maintaining the confidentiality of their own users’ names and passwords. Nigeria Police Force will not request any personal password unless user would like to use it to access a service or secured pages.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Data Deletion and User Accounts",
      content: [
        {
          text: "The Nigeria Police Force mobile application does not create, manage, or store local user profiles. Authentication is securely handled via NINAuth, an independent national digital identity service. Nigeria Police Force does not control NINAuth accounts or the personal data managed within that ecosystem. Personal information received through NINAuth is used strictly to verify your identity and process the official government services you request.",
          type: "paragraph",
        },
        {
          text: "Government Records and Retention: Service applications, requests, supporting documents, and related records submitted through the application form part of official government archives. In compliance with applicable Nigerian law and government record-retention regulations, these official records cannot be deleted upon individual request.",
          type: "paragraph",
        },
        {
          text: "Managing Your Data & Contact Us: If you wish to manage your digital identity or profile data, please contact NINAuth directly. For any questions regarding how Nigeria Police Force processes your service requests or to exercise your rights under applicable data protection laws, please reach out to us at mail@npf.gov.ng",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Amendment of Privacy Policy",
      content: [
        {
          text: "Nigeria Police Force may make some adjustments in the Privacy Policy to accommodate changes in the legal and regulatory requirements, business requirement for upgrading technologies and applications, or for service improvement. Nigeria Police Force reserves the right to make any radical or slight modification of the content of this document at any time and without prior notice. Continue to use the Site means your acceptance of such changes. Please review this Policy periodically. In case of radical changes in this Policy, we will inform you via email or by means of a notice in our Homepage.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Nigeria Police Force App Permissions",
      content: [
        {
          text: "Nigeria Police Force’s app collects location data to enable features like Report Accident, Drive mode, Rescue Me, My Map and Sail Safely. Our Sale Safely feature also requires Background Location Permission for the better use of the feature.",
          type: "paragraph",
        },
        {
          text: "We use this information to provide the requested location-based Service, not to identify you but to:",
          type: "paragraph",
        },
        {
          type: "list",
          intro:
            "We use this information to provide the requested location-based Service, not to identify you but to:",
          items: [
            "Provide you accurate service access based upon your location.",
            "Provide you some important information like nearby Police Stations and more.",
          ],
        },
      ],
    },
    {
      title: "Contact Us",
      content: [
        {
          link: {
            href: "mailto:mail@npf.gov.ng",
            label: "mail@npf.gov.ng",
          },
          text: "If you have any questions or suggestions regarding our privacy policy, please contact us at ",
          type: "paragraph",
          afterText: ".",
        },
      ],
    },
  ],
};

export const termsConditions = {
  title: "Terms & Conditions",
  sections: [
    {
      title: "Copyrights",
      content: [
        {
          text: "Copyright ©2020 Nigeria Police Force, All Rights Reserved. Any rights not expressly granted herein are reserved. No copyrighted material may be distributed, downloaded, modified, reused, copied, reproduced, transferred, displayed, reposted, transmitted, disseminated, sold, published, broadcast or circulated or otherwise used except as expressly stated either in such materials or in this notice without the express written permission of Nigeria Police Force.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Trademarks",
      content: [
        {
          text: "The marks or logos appearing through this web site are proprietary of Nigeria Police Force. You are prohibited from using any of the marks or logos without permission from Nigeria Police Force, except as permitted by applicable law.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Possible Errors and Revisions",
      content: [
        {
          text: "The information, materials, software, products and services (collectivity data) included in or available through Nigeria Police Force website and services may be superseded and/or may include inaccuracies or typographical errors. Changes are periodically made to the date contained herein.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Disclaimer of Warranties",
      content: [
        {
          text: "Nigeria Police Force website and material relating to Police information, products and services (or to third party information, products and services) is provided as is without any representation or endorsement made and without warranty of any kind, whether express or implied, including but not limited to the implied warranties of satisfactory quality, fitness for a particular purpose non-infringement, compatibility, security and accuracy. The information on this site is provided for convince as part of the service we offer at this website.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Disclaimer of Liability",
      content: [
        {
          text: "In no event will Nigeria Police Force be liable for any damages whatsoever, but not limited to any direct, incidental, consequential, special, exemplary or other indirect damages arising out of the use of or inability to use the site, the services or the content; any transaction conducted through or facilitated by the site; any claim attributable to errors, omissions, or other inaccuracies in the site.",
          type: "paragraph",
        },
        {
          text: "The service and/or content, unauthorized access to or alteration of your transmissions or data or any other matter relating to the site, the service or the content even if Nigeria Police Force has been advised of the possibility of such damages or losses. If you are dissatisfied with the site, the content, or with the terms of use, your sole and exclusive remedy is to discontinue using the site.",
          type: "paragraph",
        },
        {
          text: "Links on this Web Site to third party web sites or information are provided solely as a convenience to you. We will make every effort to clearly indicate that you are leaving Nigeria Police Force website to go to a linked site but by definition links on Nigeria Police Force website will lead to other web sites which are not under our control and you are subject to the terms of use and privacy policy applicable to those web sites. We are not responsible for the content of any linked site. We cannot guarantee that these links will work all of the time and have no control over the availability of the linked pages. Visitors who rely on this information do so at their own risk.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "No Unlawful or Prohibited Use",
      content: [
        {
          text: "As a condition of your use of Nigeria Police Force Website, you warrant to Nigeria Police Force that you will not use Nigeria Police Force Website for any purpose that is unlawful or that is prohibited by these terms of use and notices. You may not use Nigeria Police Force Website in any manner which could damage, disable, overburden, or impair the Web site and servers. You may not use Nigeria Police Force Website or servers to publish, post, distribute or disseminate any defamatory, obscene or otherwise unlawful material or information, including another's proprietary information, including trademarks or copyrighted information, without express authorization from the rights holder.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Privacy",
      content: [
        {
          text: "Nigeria Police Force Website, servers and computer system may be monitored for all lawful purposes, including to ensure that their use is authorized, to manage the Web site, server and computer system, to facilitate protection against unauthorized access, and to verify security procedures, survivability and operational security. All information (including without limitation, personal information and electronic communications) placed on or sent over this Web site, server or computer system may be monitored by Nigeria Police Force. The unauthorized use of the Web site, server or computer system may subject you to criminal prosecution. Please read the Nigeria Police Force Web Site Privacy Policy that addresses other privacy issues associated with Nigeria Police Force Website.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Password Security",
      content: [
        {
          text: "If you are registered with Nigeria Police Force Web Site for accessing online services, you are responsible for maintaining the confidentiality of your member identification and password information and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your member identification and password.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Virus protection",
      content: [
        {
          text: "We make every effort to check and test material at all stages of production. It is always wise for you to run an anti-virus program on all material downloaded from the internet. We cannot accept any responsibility for any loss, disruption or damage to your data or your computer system which may occur whilst using material derived from this website.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Governing Law",
      content: [
        {
          text: "This Agreement is entered into in the Territory of Federal Republic of Nigeria and shall be governed by and constructed in accordance with the laws of the Federal Republic of Nigeria.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Modifications",
      content: [
        {
          text: "Nigeria Police Force may amend or modify this agreement or impose new conditions at any time. Any use of the Web site by you after such notice shall be deemed to constitute acceptance by you of such amendments, modifications or new conditions. You are responsible for regularly reviewing these terms, conditions and notices.",
          type: "paragraph",
        },
      ],
    },
    {
      title: "Settlement of Disputes Relating Electronic Payment",
      content: [
        {
          text: 'To make sure you get "Nigeria Police Force" services that require electronic payment, legally and safely, avoid payment through an intermediary or by using a credit card or direct debit and/or using other means of payment that belong to third parties, without their consent.',
          type: "paragraph",
        },
        {
          text: "In case of violation of the above and/or complaint from the rightful owner of the means of electronic payment used, the client (whether natural or legal person) is subject to legal accountability and is punished by imprisonment and payment of fine, or by either, in accordance with sections 24 to 27 of the Cybercrimes (Prohibition, Prevention, etc.) Act, 2015, without prejudice to the right of Nigeria Police Force in exercising all means of legal protection and rights available and/or granted to it under the law.",
          type: "paragraph",
        },
      ],
    },
  ],
};

export const customerServiceAgreement = {
  title: "Customer Service Agreement",
  sections: [
    {
      title: "An Employee Proud to deliver distinguished service",
      content: [
        {
          type: "list",
          items: [
            "Greet you and offer attentive and unbiased service.",
            "Provide distinguished and high quality service",
            "Serve your needs adequately and professionally",
            "Understand your needs, assist and advice you for an effective problem solving and service delivery",
          ],
        },
      ],
    },
    {
      title: "An entity pledged to make customers happy",
      content: [
        {
          type: "list",
          items: [
            "Provide qualified and highly trained employees",
            "Simplify procedures to enhance the quality of customer s journey",
            "Provide Smart, Digital and E Services on a 24 hour basis",
            "Provide Service Completion requirements and completion details",
            "Provide transparency",
            "Give priority to serious cases, to the Persons with Disabilities and to the elderly",
            "Efficient and humane treatment especially of victims of offences",
            "Accept opinions, receive and handle complaints and remarks.",
          ],
        },
      ],
    },
    {
      title: "Positive and proactive customer",
      content: [
        {
          type: "list",
          items: [
            "Abide by the law",
            "Appreciate employee s efforts",
            "Provide required documents",
            "Provide your up to date information on our database",
            "Understand our priority system",
            "Call 112 only in case of emergency",
            "Respond to our inquiries",
            "Offer constructive feedback and suggestions",
          ],
        },
      ],
    },
    {
      title: "Disclaimer of Warranties",
      content: [
        {
          text: "Nigeria Police Force website and material relating to Police information, products and services (or to third party information, products and services) is provided as is without any representation or endorsement made and without warranty of any kind, whether express or implied, including but not limited to the implied warranties of satisfactory quality, fitness for a particular purpose non-infringement, compatibility security and accuracy. The information on this site is provided for convenience as part of the service we offer at this website.",
          type: "paragraph",
        },
      ],
    },
  ],
};

export const contactUs = {
  intro: "Reach Nigeria Police Force 24/7",
  reach: {
    title: "Reach Nigeria Police Force Anytime, Anywhere",
    description:
      "Connect instantly with Nigeria Police Force for emergency or non-emergency support through our dedicated channels — available 24 hours a day.",
    lines: [
      {
        number: "112",
        title: "Emergency",
        description: "For immediate police assistance in any emergency.",
      },
      {
        number: "122",
        title: "Road Safety",
        description:
          "For road traffic crashes, obstructions and highway assistance.",
      },
    ],
    signLanguage: {
      title: "Sign Language",
      subTitle:
        "A dedicated service for people who are Deaf, hard of hearing, or have speech difficulties.",
      description:
        "Connect with Nigeria Police Force through the Sign Language Service for accessible communication assistance.",
    },
  },
  feedback: {
    title: "Feedback And Complaints",
    subTitle:
      "We value every opinion, suggestion, and concern shared by our community — each helps us serve you better.",
    description:
      "Please note: under section 140 of the Penal Code Act, Cap. P3 LFN 2004, knowingly submitting a false complaint is an offence.",
    kinds: [
      {
        title: "Suggestion",
        description:
          "Your suggestion contributes to the ongoing improvement of our services.",
      },
      {
        title: "Remark",
        description:
          "Share your appreciation for a Nigeria Police Force Officer or team member who made a positive difference. Your words motivate us to do even better.",
      },
      {
        title: "Complaint",
        description:
          "Our IT support team is ready to help you resolve issues quickly and ensure your digital experience with Nigeria Police Force runs smoothly.",
      },
    ],
  },
  leaders: {
    title: "Contact",
    titleMain: "Nigeria Police Force Leadership",
    description:
      "This is a digital service that promotes communication between the senior leadership at Nigeria Police Force and the public. Eliminating all administrative barriers and obstacles to ensure that the leaders respond to queries and remarks accordingly.",
  },
};

/**
 * The Command's public counters: the Area Commands that supervise a slice of
 * the Territory, and the Divisional Headquarters where a report is actually
 * taken. Addresses and coverage are real; the photographs are placeholders.
 */
export const customerCenters = [
  {
    name: "Central Area Command",
    address: "Area 10, Garki",
    area: "Abuja Municipal",
    about:
      "The senior command for the city centre, supervising the Garki, Wuse, Maitama and Asokoro divisions. It holds the Command's central charge office and the desks that take reports the divisions refer upward.",
    kind: "Area Command",
    timing: "24 hours",
    image: "/cms/7645_D9_85_D8_B1_D9_83_D8_B2_D8_A7_D9_84_D8_A8_D8_B1_D8_B4_D8_A7_D8_A1_705bc8ce9b.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.035,7.49",
  },
  {
    name: "Gwagwalada Area Command",
    address: "Secretariat Road, Gwagwalada",
    area: "Gwagwalada",
    about:
      "Covers the Gwagwalada Area Council and the university town around it, including the stretch of the Abuja–Lokoja highway that runs through the council.",
    kind: "Area Command",
    timing: "24 hours",
    image: "/cms/3152_KRM_9488_cf562f8589.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=8.943,7.08",
  },
  {
    name: "Bwari Area Command",
    address: "Kubwa Road, Bwari",
    area: "Bwari",
    about:
      "Responsible for Bwari town, Dutse-Alhaji and the hill settlements north of the city, with a standing patrol on the Bwari–Dutse road.",
    kind: "Area Command",
    timing: "24 hours",
    image: "/cms/6176_KRM_8062_50432d72da.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.282,7.38",
  },
  {
    name: "Kubwa Area Command",
    address: "Phase 2, Kubwa",
    area: "Bwari",
    about:
      "One of the busiest commands in the Territory, covering Kubwa, Byazhin and the expressway that carries the morning traffic into the city.",
    kind: "Area Command",
    timing: "24 hours",
    image: "/cms/3193_image_7516066b91.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.156,7.326",
  },
  {
    name: "Karu Area Command",
    address: "Nyanya–Karu Road, Nyanya",
    area: "Abuja Municipal",
    about:
      "Covers the eastern corridor at the Nasarawa boundary — Nyanya, Karu, Jikwoyi and Karshi — where the Territory's largest commuter population lives.",
    kind: "Area Command",
    timing: "24 hours",
    image: "/cms/6519_MN_1448_832x440_388961a3ed.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.01,7.59",
  },
  {
    name: "Kuje Area Command",
    address: "Kuje Town, off Kuje Road",
    area: "Kuje",
    about:
      "Covers the Kuje Area Council, its farm settlements and the road that links the council to the airport corridor.",
    kind: "Area Command",
    timing: "24 hours",
    image: "/cms/4513_N_B02736_832x440_450c673242.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=8.879,7.227",
  },
  {
    name: "Garki Division",
    address: "Area 3, Garki",
    area: "Abuja Municipal",
    about:
      "One of the oldest divisions in the Territory, serving Areas 1 to 11, the ministries around them and the Garki market.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/5276_2_1_832x440_qq_59ebc12b9e.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.0333,7.4833",
  },
  {
    name: "Wuse Division",
    address: "Zone 3, Wuse",
    area: "Abuja Municipal",
    about:
      "Serves the Wuse zones and the Wuse market, and runs the beat that covers the banks and offices along Aminu Kano Crescent.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/7038_3_M7_A5995_ac1d088ee2.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.0667,7.4667",
  },
  {
    name: "Wuse II Division",
    address: "Nouakchott Street, Wuse II",
    area: "Abuja Municipal",
    about:
      "Covers Wuse II and the embassies, hotels and night-time economy along Adetokunbo Ademola Crescent.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/4377_N_B03597_optimized_f2d96b90c9.png",
    map: "https://www.google.com/maps/search/?api=1&query=9.0765,7.474",
  },
  {
    name: "Maitama Division",
    address: "Lungi Street, Maitama",
    area: "Abuja Municipal",
    about:
      "Serves Maitama, Mpape and the diplomatic quarter, working closely with the Command's protection duties.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/3619_N_B04394_5e9017812e.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.085,7.49",
  },
  {
    name: "Asokoro Division",
    address: "Yakubu Gowon Crescent, Asokoro",
    area: "Abuja Municipal",
    about:
      "Covers Asokoro and Guzape, including the residences of government officials and the approach roads to the Presidential Villa.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/7718_N_B02505_1_832x600_6c1d155fb6.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.04,7.52",
  },
  {
    name: "Utako Division",
    address: "Ekukinam Street, Utako",
    area: "Abuja Municipal",
    about:
      "Serves Utako, the Utako market and the motor park, and the office blocks along the Jabi–Utako link.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/5967_N_B04285_832x440_f0fd1f25ef.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.07,7.438",
  },
  {
    name: "Jabi Division",
    address: "Jabi District, off Bala Sokoto Way",
    area: "Abuja Municipal",
    about:
      "Covers the Jabi district, the lake front and the shopping centre, and runs the marine patrol point on Jabi Lake.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/1737_N_B111_832x440_eb376c7ae5.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.064,7.427",
  },
  {
    name: "Life Camp Division",
    address: "Life Camp, Gwarinpa",
    area: "Abuja Municipal",
    about:
      "Serves Life Camp, Kado and the Nigeria Police Force estates around them.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/6706_N_B00942_eb37e765de.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.093,7.423",
  },
  {
    name: "Gwarinpa Division",
    address: "3rd Avenue, Gwarinpa Estate",
    area: "Abuja Municipal",
    about:
      "Covers Gwarinpa, the largest housing estate in West Africa, and the district roads running through its seven avenues.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/2375_3_M7_A4443_35ae9361a2.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.108,7.405",
  },
  {
    name: "Karmo Division",
    address: "Karmo Village, off Kubwa Expressway",
    area: "Abuja Municipal",
    about:
      "Serves Karmo and the settlements along the Kubwa expressway service lanes.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/5871_3_M7_A4020_HDR_cb49d254e2.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.098,7.445",
  },
  {
    name: "Dei-Dei Division",
    address: "Dei-Dei Building Materials Market",
    area: "Abuja Municipal",
    about:
      "Covers Dei-Dei, its timber and building-materials markets, and the heavy-goods traffic that feeds them.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/3031_3_M7_A5690_faf65a9220.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.12,7.33",
  },
  {
    name: "Zuba Division",
    address: "Zuba Market Road, Zuba",
    area: "Gwagwalada",
    about:
      "Serves Zuba, the market and the junction where the Abuja–Kaduna and Abuja–Lokoja roads meet.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/5808_N_B04419_832x440_552369e48d.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.112,7.226",
  },
  {
    name: "Dutse-Alhaji Division",
    address: "Dutse-Alhaji, off Bwari Road",
    area: "Bwari",
    about:
      "Covers Dutse-Alhaji, Kubwa village and the surrounding settlements on the northern approach.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/8307_PDP_9241_194115ff1e.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.133,7.355",
  },
  {
    name: "Lugbe Division",
    address: "FHA Estate, Lugbe",
    area: "Abuja Municipal",
    about:
      "Serves Lugbe, Pyakasa and the airport road corridor, including the service lanes either side of the expressway.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/8455_3_M7_A4544_832x440_4ae88b9d4c.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=8.988,7.372",
  },
  {
    name: "Apo Division",
    address: "Apo Legislative Quarters, Apo",
    area: "Abuja Municipal",
    about:
      "Covers Apo, Gudu and the legislative quarters, and the mechanic village at Apo.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/510_N_B02759_832x440_718691f996.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=8.995,7.46",
  },
  {
    name: "Durumi Division",
    address: "Durumi District, off Ahmadu Bello Way",
    area: "Abuja Municipal",
    about:
      "Serves Durumi, Area 1 and the Games Village, and the roads that connect them to the city centre.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/3547_3_S2_A3181_df17026e53.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.011,7.472",
  },
  {
    name: "Nyanya Division",
    address: "Nyanya–Karu Road, Nyanya",
    area: "Abuja Municipal",
    about:
      "Covers Nyanya town and the bus terminals that move commuters between the Territory and Nasarawa State every morning.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/5454_N_B02391_3_832x600_4c752f6670.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.006,7.572",
  },
  {
    name: "Airport Division",
    address: "Nnamdi Azikiwe International Airport",
    area: "Abuja Municipal",
    about:
      "Based at the airport, covering the terminals, the cargo area and the airport road, and working alongside aviation security on the airside.",
    kind: "Divisional Headquarters",
    timing: "24 hours",
    image: "/cms/7097_N_B04423_67f2cabe86.jpg",
    map: "https://www.google.com/maps/search/?api=1&query=9.0068,7.2632",
  },
];
