// Generated by scripts/gen-news.mjs — do not edit by hand.

export type NewsItem = {
  slug: string;
  title: string;
  date: string;
  summary: string;
  body: string[];
  image: string | null;
};

export const news: NewsItem[] = [
  {
    "slug": "dubai-police-and-decca-explore-stronger-cooperation-on-environmental-security",
    "title": "Dubai Police and DECCA Explore Stronger Cooperation on Environmental Security",
    "date": "2026-01-10",
    "summary": "Dubai Police and the Dubai Environment and Climate Change Authority (DECCA) have discussed ways to strengthen cooperation and enhance joint coordination in areas related to environmental protection…",
    "body": [
      "Dubai Police and the Dubai Environment and Climate Change Authority (DECCA) have discussed ways to strengthen cooperation and enhance joint coordination in areas related to environmental protection and environmental security.",
      "The discussions took place during a visit by His Excellency Ahmad Mohammad bin Thani Hareb, Director General of DECCA, to the General Department of Forensic Sciences and Criminology at Dubai Police. He was received by Major General Ahmad bin Ghalita, Director of the General Department, in the presence of senior officers and specialists from both sides.",
      "The visit reflects the shared commitment of both entities to strengthening institutional cooperation, integrating efforts in scientific environmental testing, and supporting Dubai’s strategic goals related to sustainability and environmental safety.",
      "During the meeting, both sides reviewed areas of joint work and explored how the advanced scientific and technical capabilities of Dubai Police forensic laboratories can support DECCA’s environmental initiatives. These include laboratory based environmental testing and monitoring environmental indicators using precise forensic tools and methodologies.",
      "His Excellency Ahmad Mohammad bin Thani Harib stressed DECCA’s keenness to enhance integrated cooperation with specialised government partners, highlighting Dubai Police as a key strategic partner due to its role in law enforcement and environmental protection, as well as its advanced laboratories that align with international best practices. He emphasised the shared goal of building a safer and more sustainable environment for future generations through science and knowledge.",
      "Major General Ahmad bin Ghalita underlined that environmental security is an essential part of policing responsibilities, noting that this cooperation aims to enhance the readiness of specialised teams to address environmental issues using sound scientific approaches aligned with global standards.",
      "Senior officers from both sides also highlighted the importance of scientific collaboration, research exchange, and capacity building in improving performance, protecting wildlife, combating environmental crimes, and raising the quality of technical and scientific outputs."
    ],
    "image": "/cms/news/medium_7554_3545_db4f95cc64.jpg"
  },
  {
    "slug": "dubais-esc-reviews-security-preparations-for-world-government-summit",
    "title": "Dubai’s ESC Reviews Security Preparations for World Government Summit",
    "date": "2026-01-10",
    "summary": "Dubai’s Events Security Committee (ESC) has reviewed its security and operational preparations for the upcoming World Government Summit 2026, scheduled to take place from 3 to 5 February 2026 under…",
    "body": [
      "Dubai’s Events Security Committee (ESC) has reviewed its security and operational preparations for the upcoming World Government Summit 2026, scheduled to take place from 3 to 5 February 2026 under the theme Shaping the Governments of the Future.",
      "The committee held its first coordination meeting at Emirates Towers, chaired by Major General Saif Muhair Al Mazrouei, Assistant Commander-in-Chief for Operations at Dubai Police and Head of ESC. The meeting focused on discussing organisational, operational, and on ground security measures required to ensure the success of this major global event.",
      "Participants reviewed the responsibilities and field procedures assigned to all teams involved in securing the summit, which is expected to bring together global leaders, decision makers, experts, and thought leaders from around the world. The summit aims to strengthen international cooperation, address pressing global challenges, and develop future ready policies and governance models.",
      "Major General Al Mazrouei emphasised that the meeting reflects Dubai’s commitment to strong coordination and close cooperation among all strategic partners to ensure the success of major events across the emirate. He praised the efforts of committee members at administrative, organisational, and field levels, noting their role in presenting the UAE as a global benchmark in hosting international events.",
      "He added that the World Government Summit is one of Dubai’s most prominent events, attracting senior officials from within the UAE and abroad. He stressed the importance of full readiness and urged committee members to utilise their expertise and capabilities to deliver the event at the highest standards."
    ],
    "image": "/cms/news/medium_3025_4444_efdbc2ab16.jpg"
  },
  {
    "slug": "dubai-police-brings-your-voice-is-heard-to-al-ttay",
    "title": "Dubai Police Brings ‘Your Voice Is Heard’ to Al Ttay",
    "date": "2026-01-09",
    "summary": "Dubai Police organised the ‘Your Voice Is Heard’ community initiative in the Al Ttay area as part of its ongoing efforts to strengthen communication with the public and listen directly to community…",
    "body": [
      "Dubai Police organised the ‘Your Voice Is Heard’ community initiative in the Al Ttay area as part of its ongoing efforts to strengthen communication with the public and listen directly to community feedback and suggestions.",
      "The event was organised by Al Khawaneej Police Station in collaboration with the Positive Spirit Council and several strategic partners. It aimed to bring police closer to the community, encourage open dialogue, and give residents and workers the opportunity to share their views on Dubai Police services.",
      "The event was attended by Colonel Adel Mousa Al Baloushi, Deputy Director of Al Khawaneej Police Station, and Ms Fatima Bohjair, Chairperson of the Positive Spirit Council and Head of the Cultural Diversity Section at the General Department of Community Happiness, along with a number of officers, staff members, and the Neighbourhood Police team.",
      "Around 800 workers took part in the event and benefited from a range of awareness programmes, educational talks, and sports activities designed to promote safety, wellbeing, and positive community engagement.",
      "Colonel Adel Al Baloushi said the event reflects Dubai Police’s commitment to engaging directly with the community and listening closely to people’s views. He explained that such initiatives help improve services in line with the highest standards and contribute to building trust between the police and the public. He added that Dubai Police works closely with other government entities to deliver integrated services that support quality of life across Dubai.",
      "Ms Fatima Bohjair said the event was held alongside the Al Khawaneej Community Forum organised by the Council to further strengthen ties with the community. She noted that these initiatives promote tolerance, positive coexistence, constructive dialogue, and healthy lifestyles, highlighting sport as an effective social tool within residential areas."
    ],
    "image": "/cms/news/medium_9206_3464_aead92bdfa.jpg"
  },
  {
    "slug": "dubai-police-recognises-outstanding-officers-for-their-dedication-and-service",
    "title": "Dubai Police Recognises Outstanding Officers for Their Dedication and Service",
    "date": "2026-01-09",
    "summary": "Dubai Police has honoured a group of outstanding officers from the General Department of Criminal Investigation in recognition of their dedication, professionalism, and daily efforts to keep Dubai…",
    "body": [
      "Dubai Police has honoured a group of outstanding officers from the General Department of Criminal Investigation in recognition of their dedication, professionalism, and daily efforts to keep Dubai safe.",
      "The recognition ceremony was led by Major General Hareb Muhammad Al Shamsi, Deputy Commander-in-Chief for Criminal Sector Affairs at Dubai Police, and attended by Major General Eid Muhammad Thani, Assistant Commander-in-Chief for Criminal Investigation Affairs.",
      "During the ceremony, Major General Al Shamsi conveyed the appreciation and greetings of His Excellency Lieutenant General Abdulla Khalifa Al Marri, Commander-in-Chief of Dubai Police. He praised the honoured officers for their strong sense of responsibility and commitment, noting that their work reflects the values and professionalism that Dubai Police is known for.",
      "Major General Al Shamsi expressed pride in the field teams, describing them as dedicated professionals who give their best every day to serve the community. He highlighted that their efforts have played a direct role in strengthening safety and stability across Dubai and in reinforcing the emirate’s reputation as a global benchmark in security and policing.",
      "He added that the honoured officers set a positive example through teamwork, discipline, and integrity, stressing that success in police work is achieved through cooperation and shared responsibility across all departments.",
      "He concluded by wishing the honoured officers continued success and encouraging them to maintain their high standards of performance and service.",
      "The honoured officers expressed their gratitude to Dubai Police leadership for the recognition, affirming their pride in serving the community and their commitment to continuing their work with dedication and teamwork to ensure the safety and wellbeing of everyone in Dubai."
    ],
    "image": "/cms/news/medium_812_768_bc4b6467e0.jpg"
  },
  {
    "slug": "dont-miss-dubai-police-carnival-this-friday-at-city-walk",
    "title": "Don’t Miss Dubai Police Carnival this Friday at City Walk",
    "date": "2026-01-08",
    "summary": "Dubai Police invites families, friends, and visitors to enjoy the Dubai Police Carnival, opening tomorrow Friday at City Walk as part of the Dubai Shopping Festival.",
    "body": [
      "Dubai Police invites families, friends, and visitors to enjoy the Dubai Police Carnival, opening tomorrow Friday at City Walk as part of the Dubai Shopping Festival.",
      "Running for three days from 4:00 pm to 10:00 pm, the carnival promises lively entertainment, hands on experiences, and exciting attractions for all ages, bringing the community closer to the world of policing in a fun and welcoming setting.",
      "Brigadier Ali Khalfan Al Mansouri, Director of the General Department of Community Happiness, said the carnival reflects Dubai Police’s commitment to open communication with the public and to creating enjoyable experiences that promote safety, trust, and community happiness.",
      "Discover Services That Matter",
      "Visitors can explore a wide range of police and community services, including the Dubai Police smart app, volunteering opportunities through the national volunteering platform, home security services, cybercrime awareness through the e-Crime Hub, reporting services via Police Eye, lost and found services, enquiries on alerts and travel bans, and the Aman Roads platform dedicated to road safety.",
      "The Dubai Police Museum will also welcome guests to discover the story of policing in Dubai, highlighting key milestones in security and technology over the years.",
      "Enjoy Live Shows and Interactive Experiences",
      "The carnival features motorcycle and bicycle performances, live music by the Dubai Police Academy band, police dog shows, luxury tourist patrol vehicles, and an immersive virtual reality experience inside the Ghiath patrol car. Visitors can also view heritage displays such as a classic Land Rover, the Ramadan cannon, and special exhibits from the UAE SWAT Challenge, including an armoured vehicle and diving suit.",
      "A Treat for Families and Children",
      "Children and families can enjoy creative workshops at the Makers Studio, interactive digital games, sports activities, puzzles, competitions, and gifts at the Khalid Children’s Magazine platform.",
      "The Dubai Police Carnival offers a perfect opportunity to spend quality time with family, enjoy unique experiences, and get to know police services in a relaxed and engaging atmosphere at City Walk."
    ],
    "image": "/cms/news/medium_4062_3534_ac916f2277.jpg"
  },
  {
    "slug": "al-barsha-police-station-hosts-your-voice-is-heard-community-initiative",
    "title": "Al Barsha Police Station Hosts ‘Your Voice Is Heard’ Community Initiative",
    "date": "2026-01-08",
    "summary": "Dubai Police, represented by Al Barsha Police Station, organised the ‘Your Voice Is Heard’ initiative as part of its ongoing efforts to strengthen direct communication with residents, partners, and…",
    "body": [
      "Dubai Police, represented by Al Barsha Police Station, organised the ‘Your Voice Is Heard’ initiative as part of its ongoing efforts to strengthen direct communication with residents, partners, and community members within the station’s jurisdiction.",
      "The forum provided an open platform for attendees to share their views, feedback, and development suggestions, reinforcing Dubai Police’s commitment to listening closely to the community and responding to their needs.",
      "The event was attended by Colonel Yousif Thani Muhammad Al Muhairi, Deputy Director of Al Barsha Police Station, alongside a number of officers, residents, and partners.",
      "Colonel Al Muhairi emphasised that the ‘Your Voice Is Heard’ forum reflects Dubai Police’s approach, guided by the directives of Lieutenant General Abdulla Khalifa Al Marri, Commander-in-Chief of Dubai Police, to engage directly with the public and benefit from their feedback to continuously enhance services in line with the highest international standards.",
      "He explained that all feedback and suggestions received from community members are carefully reviewed and followed up, supporting government directions to reduce bureaucracy and raise service efficiency.",
      "During the forum, attendees were introduced to several Dubai Police initiatives aimed at strengthening community engagement, including the ‘Your Neighbourhood Police Officer’ initiative, which serves as a direct link between the police and the community to promote cooperation and build a safer society.",
      "The session also featured an overview of Dubai Police’s community and security services available at police stations, through the official website, the smart application, and Smart Police Stations SPS. Participants were additionally briefed on the role of the 901-contact centre for non-emergency calls and the 999-emergency number, which is dedicated exclusively to urgent cases.",
      "At the conclusion of the initiative, Colonel Al Muhairi honoured Al Barsha Police Station’s partners who have supported various events and initiatives, praising their cooperation and valuable contributions."
    ],
    "image": "/cms/news/medium_9349_56565_421a62086b.jpg"
  },
  {
    "slug": "dubai-police-highlight-role-of-trainers-in-building-future-readiness-during-4th-",
    "title": "Dubai Police Highlight Role of Trainers in Building Future Readiness During 4th Trainers",
    "date": "2026-01-08",
    "summary": "Dubai Police held the Fourth Trainers Forum at the Dubai Police Officers Club under the theme “Sustainable Readiness and a Trainer Who Makes the Difference”, highlighting the important role trainers…",
    "body": [
      "Dubai Police held the Fourth Trainers Forum at the Dubai Police Officers Club under the theme “Sustainable Readiness and a Trainer Who Makes the Difference”, highlighting the important role trainers play in preparing police teams and building future skills.",
      "Lt General Abdulla Khalifa Al Marri, Commander-in-Chief of Dubai Police, attended the opening of the forum, alongside Major General Hareb Al Shamsi, Deputy Commander-in-Chief for Criminal Sector Affairs, and Dr Major General Ahmad Zaal Bin Krishan Almuhairi, Deputy Commander-in-Chief for Financial and Administrative Sector Affairs.",
      "Organised by the General Department of Training, the forum reflects Dubai Police’s commitment to continuous development, modern training approaches, and strengthening readiness to meet future challenges.",
      "During the opening, Lt General Abdullah Al Marri praised the efforts of trainers, noting that Dubai Police’s achievements locally and internationally are closely linked to their dedication and professionalism. He stressed that training is a key pillar of effective policing, as trainers help develop skills, share experience, and prepare officers to deal confidently with real situations.",
      "He added that Dubai Police places strong focus on ongoing training to improve performance, encourage innovation, and provide high quality services to the community.",
      "The forum featured speakers from several local and international organisations, including training and security institutions from the United States and Brazil, as well as national academic and education bodies. Sessions and workshops focused on practical training, safety, decision making, and sharing best practices.",
      "Brigadier Ahmad Mirdas, Director of the General Department of Training, said the forum reflects Dubai Police’s focus on investing in people and building a strong and future ready training system. He highlighted the role of trainers in shaping professional teams and supporting operational readiness.",
      "Colonel Sulaiman Abdullah Al Ameri, Director of the Programme Design and Development Department and the forum’s general coordinator, explained that the sessions were designed to be practical and relevant, combining theory with hands on application.",
      "The forum concluded with the honouring of speakers, session moderators, senior trainers, trainers of trainers, and the best trainers across various fields for 2025."
    ],
    "image": "/cms/news/medium_5367_34543_9ffb7201d7.jpg"
  },
  {
    "slug": "dubai-police-academy-celebrates-top-achiever-with-ceremonial-parade-in-jumeirah",
    "title": "Dubai Police Academy Celebrates Top Achiever with Ceremonial Parade in Jumeirah",
    "date": "2026-01-07",
    "summary": "Residents of Jumeirah joined a proud community celebration yesterday (Tuesday) evening as Dubai Police Academy launched the first of its pre-graduation events for the 33rd cohort of cadets and the…",
    "body": [
      "Residents of Jumeirah joined a proud community celebration yesterday (Tuesday) evening as Dubai Police Academy launched the first of its pre-graduation events for the 33rd cohort of cadets and the 6th cohort of female cadets for the academic year 2025 to 2026.",
      "The event paid special tribute to cadet Musbah Khamis Al Muhairi, who ranked first overall and first in military training. In a gesture of appreciation and recognition, a ceremonial military parade was organised in his neighbourhood, allowing his family and neighbours to share in the celebration of his exceptional achievement.",
      "The programme featured impressive field demonstrations by academy cadets, showcasing strong discipline, precision, and coordination. Attendees also enjoyed displays by luxury tourist security patrols, alongside musical performances by the Dubai Police Academy band, creating an engaging and festive atmosphere.",
      "The pre-graduation activities will continue at several locations across Dubai. On 9 January, land and marine parades will take place at Bluewaters Island and Ain Dubai. A third event is scheduled for 15 January in Al Khawaneej. These activities aim to reinforce Dubai Police’s community presence and strengthen positive interaction with the public.",
      "Brigadier Dr Sultan Al Jammal, Director of the Dubai Police Academy, said that the academy remains committed to developing security leaders who combine professional competence with strong national values and high levels of discipline. He highlighted that such community events reflect the role of police officers as active partners in society, strengthening public trust and reinforcing the bond between the community and the security sector.",
      "He added that the academy ensures its graduates embody discipline, loyalty, and innovation, noting that every officer represents a future leader entrusted with protecting the nation’s security and prosperity."
    ],
    "image": "/cms/news/medium_3413_805_a23f92c930.jpg"
  },
  {
    "slug": "2-479-volunteers-support-crowd-management-across-dubai-on-new-years-eve",
    "title": "2,479 Volunteers Support Crowd Management Across Dubai on New Year’s Eve",
    "date": "2026-01-07",
    "summary": "Dubai Police have praised the outstanding efforts of volunteers who supported crowd management and organisation during the New Year’s Eve 2026 celebrations, describing their contribution as a key…",
    "body": [
      "Dubai Police have praised the outstanding efforts of volunteers who supported crowd management and organisation during the New Year’s Eve 2026 celebrations, describing their contribution as a key factor in the smooth and safe delivery of one of the city’s largest annual events.",
      "Brigadier Ali Khalfan Al Mansouri, Director of the General Department of Community Happiness at Dubai Police, commended the volunteers for their impressive performance and high morale while providing operational support throughout the celebrations. He said their professionalism reflected Dubai’s civilised image and highlighted the strong partnership between the police and the community.",
      "Brigadier Al Mansouri stressed that these results reaffirm Dubai Police’s commitment to government directions that promote volunteering and community participation as sustainable values and a core pillar of comprehensive development. He noted that Dubai Police continue to embed volunteering as an institutional value through innovative programmes and initiatives that enable employees and community members to actively contribute to human security and social stability.",
      "He added that the volunteers’ achievements on New Year’s Eve demonstrated the integration of efforts between official entities and the community, and confirmed that volunteering has become a deeply rooted culture among both Emiratis and residents.",
      "“The volunteers showed exemplary commitment and discipline and served as a direct and effective support line for Dubai Police officers at various field deployment points,” Al Mansouri added.",
      "More than 3,111 volunteers registered to take part in support operations during the New Year’s Eve celebrations, with 2,479 selected to participate. Representing 45 nationalities, the volunteers were deployed across 15 main locations, where they successfully carried out their duties, assisted police officers, and submitted reports and observations that will help enhance future operations.",
      "Captain Saeed Al Ketbi, Director of the Community Relations Department, explained that Dubai Police’s volunteering platform operates year round, offering carefully planned opportunities that strengthen community integration in support of police duties, including security, traffic, and awareness activities. He noted that the strong turnout reflects growing public awareness of the importance of volunteering and its vital role in supporting sustainable development goals.",
      "Captain Al Ketbi also praised the leading role played by volunteer teams in promoting positive citizenship, social responsibility, and constructive partnerships between the public and private sectors. He said these partnerships have created meaningful opportunities that harness individual capabilities while contributing to the safety and stability of the community."
    ],
    "image": "/cms/news/medium_7973_804_1e4cab917b.jpg"
  },
  {
    "slug": "meet-dubai-polices-lt-doha-turning-personal-challenges-into-professional-strengt",
    "title": "Meet Dubai Police’s Lt. Doha, Turning Personal Challenges into Professional Strength",
    "date": "2026-01-07",
    "summary": "In a powerful example of Dubai Police’s commitment to investing in people and celebrating inspiring success stories, His Excellency Lieutenant General Abdulla Khalifa Al Marri, the Commander-in-chief…",
    "body": [
      "In a powerful example of Dubai Police’s commitment to investing in people and celebrating inspiring success stories, His Excellency Lieutenant General Abdulla Khalifa Al Marri, the Commander-in-chief of Dubai Police, has honoured Lieutenant Doha Ahmad Muhammad as part of ‘The Group’ initiative, which highlights outstanding and motivating role models within the force.",
      "Lieutenant Doha was recognised for her professional excellence and exceptional personal journey, which reflects the values of resilience, determination, and leadership upheld by Dubai Police. The honour underlines how challenges can be transformed into motivation for achievement and leadership.",
      "Al Marri praised the achievements Lieutenant Doha has accomplished in a relatively short period, noting that they reflect the supportive institutional environment provided by Dubai Police to empower female talent, develop their skills, and offer equal opportunities across all fields, including military training. He emphasised that she represents an inspiring example of the ambitious Emirati woman who is capable of leadership and meaningful contribution.",
      "A Journey Shaped by Resilience",
      "Lieutenant Doha grew up as an orphan, raised with her sisters in an environment of care and support. Despite the hardship of losing her parents, she refused to be defined by circumstances and chose a path of excellence through education, hard work, and self belief.",
      "After becoming a mother to her son Younes, she faced another profound loss when her husband passed away in a tragic accident. Determined to provide strength and stability for her child, she chose to move forward and applied to join Dubai Police. Her acceptance marked a turning point that launched her military career.",
      "From trainee to trainer",
      "Thanks to her discipline and outstanding performance, Lieutenant Doha was selected as leader of a group of graduates. She later joined a trainers preparation course, where she was the only woman among the participants and achieved an excellent grade. This success led to her appointment as an official trainer at the Dubai Police Academy, reflecting the institution’s confidence in its national talent and its commitment to empowering promising professionals.",
      "Lieutenant Doha described one of her most emotional moments as seeing her son Younes take part in a graduation ceremony and recite the military oath under the direct guidance of the Commander-in-Chief, a memory she says will remain with her forever.",
      "A Role Model for Trainees",
      "In her role as a trainer, Lieutenant Doha is keen to inspire female trainees by preparing a strong and confident generation capable of carrying responsibility in the field.",
      "Alongside her professional success, she continued her academic journey and earned a Master’s degree in Public Relations and Corporate Communication. She later remarried and was blessed with two daughters, completing a close and supportive family life after years of hardship.",
      "The Group initiative",
      "The Group initiative aims to highlight Dubai Police employees who have delivered outstanding efforts or lived inspiring human experiences, whether in their professional roles or personal lives. By sharing these stories, the initiative promotes positivity, resilience, and a strong sense of unity within the workplace and the wider community.",
      "Additional recognition",
      "During the ceremony, Al Marri also honoured Brigadier Nasser Hamid Al Zari in appreciation of his significant role and continuous support for Lieutenant Doha throughout her career. His leadership, field follow up, and belief in empowering female cadres have contributed to creating a motivating training environment where talent can thrive.",
      "Brigadier Al Zari affirmed that the Dubai Police Academy prioritises attracting and qualifying national talent to the highest standards, adding that Lieutenant Doha’s success is a model they are proud of and aim to replicate by preparing a new generation of capable young security leaders."
    ],
    "image": "/cms/news/medium_2006_803_eccd7bb303.jpg"
  },
  {
    "slug": "dubai-police-host-awareness-session-for-students-and-parents-on-sports-safety-et",
    "title": "Dubai Police Host Awareness Session for Students and Parents on Sports Safety & Etiquett",
    "date": "2026-01-06",
    "summary": "Dubai Police, through its Your Commitment is Happiness initiative, organized an awareness lecture for students and parents at the Dubai Chess and Culture Club.",
    "body": [
      "Dubai Police, through its Your Commitment is Happiness initiative, organized an awareness lecture for students and parents at the Dubai Chess and Culture Club.",
      "The lecture aimed to educate the sports audience on their obligations in stadiums as outlined by Federal Law No. (8) of 2014 concerning the security of sports facilities and events.",
      "It included an explanation of the Your Commitment is Happiness initiative, which seeks to enhance communication with sports fans and unify efforts to make them happy by establishing a culture of positive cheering that reflects the UAEs civilized image in sports stadiums, emphasizing the importance of spreading awareness about the limits of cheering and the danger of expressing emotions negatively towards others."
    ],
    "image": "/cms/news/medium_5116_799_e94874e74b.jpg"
  },
  {
    "slug": "dubai-police-warn-against-fraudulent-recruitment-offers-on-social-media",
    "title": "Dubai Police Warn Against Fraudulent Recruitment Offers on social media",
    "date": "2026-01-06",
    "summary": "The Anti-Fraud Centre, within the General Department of Criminal Investigation at Dubai Police, has issued a fresh warning to the public regarding fraudulent advertisements on social media platforms…",
    "body": [
      "The Anti-Fraud Centre, within the General Department of Criminal Investigation at Dubai Police, has issued a fresh warning to the public regarding fraudulent advertisements on social media platforms that falsely claim to provide recruitment and placement services for domestic workers and auxiliary staff, but are actually orchestrated by scammers seeking to illicitly obtain financial gains.",
      "Safe Recruitment Practices",
      "The Anti-Fraud Centre urges residents seeking to hire domestic help to deal exclusively with licensed and accredited recruitment offices within the UAE. The Centre strongly advises against transferring any funds to entities or individuals promoting recruitment services outside of official legal channels. Adhering to approved procedures is the only way to ensure the legal rights of all parties—the employer, the worker, and the agency—are protected.",
      "#BewareofFraud",
      "This warning is part of the ongoing #BewareofFraud campaign, which aims to enhance public vigilance against evolving criminal tactics. Dubai Police reiterated the necessity of exercising caution and verifying the legitimacy of any service provider before sharing personal information or making payments.",
      "Report Suspicious Activity",
      "To maintain a safe community, the Anti-Fraud Centre encourages the public to report any fraudulent activity or suspicious online offers immediately. Reports can be made through the following official channels:",
      "Dubai Police Smart App: Available on all major mobile platforms. eCrime Platform: The dedicated portal for reporting cybercrimes. Call Centre: Dial 901 for non-emergency inquiries and report"
    ],
    "image": "/cms/news/medium_3874_798_b120f522f2.jpg"
  },
  {
    "slug": "over-5-000-people-attend-naif-community-forum-as-dubai-police-strengthen-safety-",
    "title": "Over 5,000 People Attend Naif Community Forum as Dubai Police Strengthen Safety Awareness",
    "date": "2026-01-05",
    "summary": "More than 5,000 residents and visitors gathered for the Naif Community Forum, a vibrant event organised by Dubai Police to foster closer ties with the public and promote essential safety and traffic…",
    "body": [
      "More than 5,000 residents and visitors gathered for the Naif Community Forum, a vibrant event organised by Dubai Police to foster closer ties with the public and promote essential safety and traffic awareness.",
      "Held under the patronage of the Ministry of Interior and led by the Positive Spirit Council and Naif Police Station, the forum combined vital community education with a festive atmosphere. Families and children enjoyed a diverse programme of cultural displays, sporting activities, and entertainment, culminating in a spectacular fireworks display.",
      "Ms Fatima Buhjair, Chairperson of the Positive Spirit Council and Head of the Cultural Diversity Section, emphasised the importance of the event: The Naif Community Forum is central to Dubai Police’s mission to build meaningful bridges with all segments of our society. By promoting the values of tolerance, co-operation, and coexistence, we are working together to ensure Dubai remains the safest and happiest city in the world. Our goal is to foster a sense of shared responsibility in maintaining public security within a cohesive, multicultural environment.",
      "Engaging the Community through Awareness The forum featured several educational sessions and interactive workshops hosted by various Dubai Police departments, focusing on key public services and safety protocols:",
      "Road Safety: The General Department of Traffic provided guidance on adhering to traffic laws and maintaining public safety on the roads. Victim Support: The General Department of Police Stations highlighted the Communicate with Victim service, ensuring residents know how to access professional support. Cybersecurity: Experts from the General Department of Criminal Investigation introduced the e-Crime platform, teaching attendees how to report cyber-offences effectively. Emergency Contact: The General Department of Operations reminded the public to reserve the 999 number for emergencies only, while using 901 for general enquiries and non-emergency cases.",
      "The event also showcased the ease of accessing Dubai Police services via their official website and smart app.",
      "Key contributors to the event’s success included Captain Ahmad Al Kaabi (General Department of Anti-Narcotics), First Lieutenant Sabha Bashir (General Department of Administrative Affairs), Sergeant Omar Musallam Othman Aflaton (General Department of Traffic), and First Corporal Ahmad Mohammad Salem (General Department of Operations)."
    ],
    "image": "/cms/news/medium_6184_797_1af17ae345.jpg"
  },
  {
    "slug": "dubai-police-explores-the-future-of-sustainable-cyber-resilience-in-information-",
    "title": "Dubai Police Explores the Future of Sustainable Cyber Resilience in Information Security",
    "date": "2026-01-05",
    "summary": "Dubai Police, represented by the Information Security Centre and the Future Foresight Centre, recently hosted a high-level panel discussion entitled Foresight into Building Sustainable Cyber…",
    "body": [
      "Dubai Police, represented by the Information Security Centre and the Future Foresight Centre, recently hosted a high-level panel discussion entitled Foresight into Building Sustainable Cyber Resilience for Information Security.",
      "The session aimed to bolster collaboration between key stakeholders, elevate awareness of cyber resilience, and support strategic advancements in information security.",
      "The session was inaugurated by Brigadier Dr Expert Hamdan Al Ghasyah, Director of the Future Foresight Centre, and Lieutenant Colonel Dr Expert Saeed Thani Al Marri, Director of the Information Security Centre. The event was attended by a distinguished group of information security experts and specialists from both Dubai Police and their strategic external partners.",
      "A Strategic Vision for Future Readiness",
      "Brigadier Dr Hamdan Al Ghasyah emphasised that establishing cyber resilience is now a critical strategic path, intricately linked to an organisations ability to maintain sustainability and future readiness. He noted that a successful future vision must align cybersecurity with broader organisational objectives to ensure robust data protection and business continuity under all circumstances. Anticipating the future of the cyber landscape requires effective knowledge-sharing partnerships and the integration of specialised expertise to generate innovative, practical solutions, Brigadier Al Ghasyah stated. He further highlighted that investing in human capital is the cornerstone of a secure digital future, achieved by empowering national talent with analytical and forward-thinking capabilities.",
      "Strengthening the Digital First Line of Defence",
      "Lieutenant Colonel Dr Saeed Thani Al Marri remarked that information security serves as the primary line of defence for institutional stability and the protection of digital assets. He asserted that achieving true cyber resilience begins with building an integrated security ecosystem grounded in clear governance, precise standards, and continuous risk assessment.",
      "Security readiness demands enhancing maturity through specialised training, periodic testing, and improving response efficiency to potential cyber incidents, Lt. Col. Al Marri explained. He also stressed the importance of adopting international best practices in data protection and tailoring them to meet the unique requirements of policing, ensuring a balance between rigorous security procedures and seamless organisational performance.",
      "Discussion Themes",
      "The panel explored several pivotal themes, including:",
      "Emerging Technologies: Analysing their impact on internal information security practices. Zero Bureaucracy: Exploring future trends in streamlining security procedures without compromising safety. Empowering Personnel: Enhancing security maturity through proactive awareness and preparedness for future challenges.",
      "The session concluded with constructive dialogue and knowledge exchange, where participants reviewed best practices and addressed the opportunities and challenges of building a resilient information security framework capable of keeping pace with the rapid global evolution of the cyber domain."
    ],
    "image": "/cms/news/medium_589_796_a8d89773ba.jpg"
  },
  {
    "slug": "dubai-brings-together-60-officers-from-42-countries-in-the-third-police-innovati",
    "title": "Dubai Brings Together 60 Officers From 42 Countries in The Third Police Innovation",
    "date": "2026-01-05",
    "summary": "Dubai Police has launched the third edition of the Police Innovation and Leadership Diploma (PIL), with the participation of 60 police leaders representing 42 countries from around the world.",
    "body": [
      "Dubai Police has launched the third edition of the Police Innovation and Leadership Diploma (PIL), with the participation of 60 police leaders representing 42 countries from around the world.",
      "The programme will run from 12 January until 2 May 2026 and is organised by Dubai Police, represented by the General Department of Training, in cooperation with Rabdan Academy.",
      "The PIL diploma is the first of its kind in the region to focus on police innovation and the preparation of international police leaders. It aims to enhance leadership capabilities within law enforcement by introducing participants to advanced methodologies, innovative strategies, and future focused leadership skills.",
      "The programme also supports the development of modern policing practices, strengthens cooperation and communication among police agencies worldwide, and reinforces Dubai’s position as a global hub for security education and training.",
      "Brigadier Badran Saeed Al Shamsi, Acting Assistant Commander-in-Chief for Academic Affairs and Training and Head of the PIL Team, said that the programme reflects Dubai Police’s commitment to developing the professional and practical capabilities of participating officers. He explained that the diploma equips participants with knowledge and scientific tools aligned with global security trends, supporting the UAE and Dubai’s leading role in preparing highly qualified police leaders in line with international best practices.",
      "He added that previous editions of the diploma contributed to developing police leaders with in depth understanding of advanced areas, including police leadership and innovation, risk management and accreditation, business continuity, future foresight, police and security planning, digital transformation for financial crime prevention, organisational psychology in policing, and policing practices in smart and resilient cities.",
      "Meanwhile, Brigadier Mohammad Atiq Thani, Director of Dubai Police’s Regulatory Office and Deputy Head of the PIL Team, noted a clear increase in participation in the third edition.",
      "“The number of participants rose to 60 compared to 53 in the second edition, marking a growth of 14 percent, while the number of participating countries increased from 38 to 42, reflecting a 16 percent rise,” he said.",
      "He said this growth demonstrates the increasing international confidence in Dubai Police’s training programmes and Dubai’s status as a global destination for preparing police leaders in security, innovation, and quality of life.",
      "Brigadier Mohammad Atiq Thani explained that the diploma is built around three main pillars: the academic programme, tactical training, and physical training.",
      "“It is delivered by academic experts and international trainers, with a total of 486 training hours over 16 weeks. The programme is supported by nine main working teams comprising more than 50 staff members,” he said.",
      "He also highlighted the programme’s expanding global reach over the past three years. A total of 96 countries applied to participate, with 70 countries meeting the admission requirements. The number of applications reached 545, of which 158 participants were accepted, including 132 men and 26 women. Participating countries represent Asia, Europe, Africa, North America, and South America, underlining the diploma’s strong international standing.",
      "Brigadier Mohammad Atiq Thani added that the academic component was developed in collaboration with Rabdan Academy, one of the UAE’s leading national educational institutions specialising in defence, security, emergency management, and crisis response.",
      "“The academy delivers advanced academic and training programmes in line with the highest international standards and contributes to preparing national and international leaders through strategic partnerships with global academic and security institutions,” he confirmed."
    ],
    "image": "/cms/news/medium_7734_795_2d4283f118.jpg"
  },
  {
    "slug": "dominican-republic-makes-debut-at-uae-swat-challenge-2026",
    "title": "Dominican Republic Makes Debut at UAE SWAT Challenge 2026",
    "date": "2026-01-04",
    "summary": "Dubai, United Arab Emirates– 4 January 2026: The National Police of the Dominican Republic has announced its historic first participation in the upcoming UAE SWAT Challenge 2026. This seventh edition…",
    "body": [
      "Dubai, United Arab Emirates– 4 January 2026: The National Police of the Dominican Republic has announced its historic first participation in the upcoming UAE SWAT Challenge 2026. This seventh edition of the prestigious international event is scheduled to take place from 7 to 11 February at the Training City in Al Ruwayyah, Dubai.",
      "General Johnny Soto Abreu, Central Director of Police Operations for the Dominican Republic National Police, highlighted that the challenge serves as a significant global forum for specialised tactical units to exchange expertise and sharpen field operational skills. By engaging in high-stakes competitions, teams gain invaluable insights into the latest tactical methodologies used by elite units worldwide.",
      "It is a great honour for us to participate in the UAE SWAT Challenge in Dubai, stated General Abreu. Our team has prepared with immense dedication and discipline to ensure we perform at our very best. Beyond the spirit of competition, we view this as a primary opportunity to share knowledge with international counterparts and bolster our operational effectiveness.",
      "General Abreu further noted that the event fosters a unique sense of unity among teams who share a common mission: to protect and serve the public. Every test within the challenge is an opportunity to grow that expertise. This experience allows us to refine our teamwork, precision, and tactical readiness, which ultimately improves our rapid response capabilities back home in the Dominican Republic.",
      "Concluding his remarks, General Abreu expressed his gratitude to the organising committee: We extend our sincere thanks to the UAE SWAT Challenge organisers for their invitation and for their support in bringing together the worlds elite tactical units. From the Dominican Republic, we send our warmest greetings and best wishes for a successful event.",
      "The 2026 challenge will see the Dominican Republic join a world-class assembly of special police units, rapid intervention teams, and tactical squads, all competing in one of the most rigorous professional policing tests in the world."
    ],
    "image": "/cms/news/medium_2395_4354_267802d87e.jpg"
  },
  {
    "slug": "dubai-police-issue-warning-over-work-visa-scams",
    "title": "Dubai Police Issue Warning Over Work Visa Scams",
    "date": "2026-01-04",
    "summary": "The Anti-Fraud Centre at Dubai Police’s General Department of Criminal Investigation is urging the public to be vigilant against scammers offering fake work visas. These fraudsters often lure victims…",
    "body": [
      "The Anti-Fraud Centre at Dubai Police’s General Department of Criminal Investigation is urging the public to be vigilant against scammers offering fake work visas. These fraudsters often lure victims with hollow promises of employment and visa sponsorship that have no legal basis. As part of the ongoing #BewarOfFraud campaign, police officials are reminding everyone that the only safe way to secure a visa is through official government channels and legally licensed recruitment agencies.",
      "How to Protect Yourself",
      "To avoid falling victim to these schemes, Dubai Police recommends the following: Verify First: Always double-check the authenticity of any visa offer through the relevant official authorities before making any payments. Use Authorised Channels: Only deal with accredited offices and government platforms to process your paperwork. Stay Cautious: Be wary of individuals or unofficial groups promising guaranteed visas outside of standard legal procedures.",
      "How to Report a Scam",
      "If you have been targeted by a scammer or have spotted a suspicious offer, dont stay silent. Reporting these incidents helps protect the entire community. You can report fraud or cybercrimes through:",
      "The Dubai Police Smart App: A quick and easy way to report directly from your phone. The eCrime Platform: Specifically designed for reporting online crimes and digital fraud. Call 901: For non-emergency enquiries and to speak with a specialist."
    ],
    "image": "/cms/news/medium_1399_4646_692dbe0d5b.jpg"
  },
  {
    "slug": "dubai-police-commander-in-chief-future-readiness-is-key-to-sustainable-security-",
    "title": "Dubai Police Commander-in-Chief: Future Readiness Is Key to Sustainable Security and",
    "date": "2026-01-04",
    "summary": "His Excellency Lieutenant General Abdulla Khalifa Al Marri, Commander-in-Chief of Dubai Police, highlighted the importance of planning for the future as a fundamental part of modern government work…",
    "body": [
      "His Excellency Lieutenant General Abdulla Khalifa Al Marri, Commander-in-Chief of Dubai Police, highlighted the importance of planning for the future as a fundamental part of modern government work and a key factor in ensuring the continuity of services and the development of institutional performance.",
      "He emphasised that future foresight plays a vital role in helping organisations stay ready for change, anticipate challenges, and respond to them efficiently. He also underlined the important contribution of the Future Foresight Centre in spreading a culture of future readiness and building an integrated system that supports proactive planning and flexible decision making.",
      "Al Marri explained that Dubai Police follows a comprehensive and structured approach to future foresight, aimed at setting a clear long-term vision for all security projects and linking them directly to strategic goals. This approach enhances readiness for future developments and ensures that security planning keeps pace with rapid changes. He also pointed to the growing role of artificial intelligence and predictive analytics in strengthening foresight tools and supporting security related decision making.",
      "These remarks were made during his inspection visit to the Future Foresight Centre as part of the annual inspection programme covering general departments and police stations. The visit was attended by Major General Saif bin Abed, Assistant Commander-in-Chief for Excellence and Pioneering Affairs, Brigadier Dr Hamdan Al Ghassia, Director of the Future Foresight Centre, Brigadier Dr Ibrahim bin Siba’a, Deputy Director of the General Department of Excellence and Pioneering, Brigadier Ahmad Al Muhairi, Director of the Inspection and Control Department, Lieutenant Colonel Omar Al Suwaidi, Deputy Director of the Future Foresight Centre, Lieutenant Colonel Dr Abdulrazzaq Abdulrahim, Head of the Inspection Section, in addition to several officers.",
      "During the visit, Al Marri reviewed the Future Foresight Centre’s strategic plan for the period from 2025 to 2030. The plan is aligned with the UAE Future Foresight Strategy and closely linked to Dubai Police’s overall strategy. The centre successfully achieved 38 performance indicators with a completion rate of 100 percent, reflecting the maturity of its foresight framework and the effectiveness of its planning and implementation.",
      "He was also briefed on future readiness indicators across the Administrative and Financial Affairs Sector and the Criminal Investigation Sector, as well as key readiness pillars. These included organisational agility and change management, future foresight and design, the use of data and technology, future talent development, and innovation for the future. In addition, he reviewed several digital transformation projects aimed at improving operational efficiency and supporting smart policing.",
      "The centre showcased 37 approved future focused projects implemented across different sectors. It also highlighted its achievements in producing 30 future visions, 69 foresight reports, and 14 future studies, alongside the development of future scenarios and risk reports. These efforts contribute to comprehensive foresight across policing operations and help strengthen institutional readiness.",
      "As part of its efforts to build capabilities and promote a culture of future readiness, the centre delivered training courses and awareness workshops targeting seven key sectors. In addition, 59 employees from various sectors completed the Professional Diploma in Future Readiness Foresight, supporting greater institutional awareness and the practical application of foresight concepts.",
      "At the conclusion of the inspection, Lieutenant General Al Marri praised the clear progress and positive change achieved by the Future Foresight Centre. He noted that this reflects Dubai Police’s commitment to continuous development, keeping pace with leading local and international practices, and strengthening cooperation across sectors to maintain excellence in security work.",
      "He also met with participants of the Professional Diploma in Future Readiness Foresight, encouraging them to apply their academic and practical knowledge to further embed foresight thinking and proactive readiness across all departments and sectors of Dubai Police."
    ],
    "image": "/cms/news/medium_6484_32434_e27364c17f.jpg"
  },
  {
    "slug": "meet-dubai-police-captain-al-marri-hero-of-challenge-71",
    "title": "Meet Dubai Police Captain Al Marri, Hero of Challenge 71",
    "date": "2026-01-03",
    "summary": "Captain Dr Engineer Salem Al Marri of Dubai Police has emerged as a powerful example of ambition, commitment, and forward-thinking leadership. His story combines academic excellence with professional…",
    "body": [
      "Captain Dr Engineer Salem Al Marri of Dubai Police has emerged as a powerful example of ambition, commitment, and forward-thinking leadership. His story combines academic excellence with professional dedication and culminated in a major national achievement when he was crowned champion of the first edition of the Challenge 71 for Young Government Leaders.",
      "The winner was announced in November 2025 by His Highness Hamdan bin Mohammed bin Rashid Al Maktoum, Crown Prince of Dubai, Deputy Prime Minister and Minister of Defence, and Chairman of the Executive Council of Dubai. The announcement followed a highly competitive journey in which Captain Al Marri and his team successfully progressed through every stage of the challenge, eventually securing first place in the final round. His Highness personally named him the champion of the inaugural edition.",
      "A strong academic and professional foundation",
      "Captain Al Marri joined Dubai Police in 2016 and began his career in the General Department of Artificial Intelligence before moving to the General Department of Anti-Narcotics. Across both roles, he demonstrated strong professional performance and administrative capability.",
      "His academic journey began earlier, when he was sponsored by Dubai Police in 2012 to study electronic engineering. He later completed a master’s degree in electrical engineering, producing a thesis between 2017 and 2025 on facial expression recognition using artificial intelligence.",
      "Building on this foundation, Captain Al Marri became the first Emirati to earn a PhD from Mohamed bin Zayed University of Artificial Intelligence, specialising in computer vision. His work in future technologies earned him the Individual Excellence Medal in Science and Future Technology, recognising his contribution to advancing artificial intelligence and computer vision applications.",
      "In 2022, he also became a member of the Dubai Youth Council, where he took part in several impactful initiatives. The council was later recognised as the best youth council in the country. In the same spirit of achievement, he received the Mother of the Nation Medal in the Science and Future Technology category, honouring excellence in innovation across scientific, social, and development fields.",
      "Inside the Challenge 71 experience",
      "Captain Al Marri joined the first edition of the Challenge 71 for Young Government Leaders alongside participants from local and federal government entities. In total, 32 participants took part, with each stage eliminating half the competitors, making the challenge both demanding and intense.",
      "The first stage focused on developing solutions linked to recovery from drug addiction. This was followed by Resilience Week, where teams were placed under significant pressure to design response plans for emergency situations. Participants had to address the spread of rumours, manage social media during crises, and choose effective communication and response strategies.",
      "Teams that advanced were then challenged during an evening round held at the Museum of the Future. Here, they were tasked with designing a sustainable space station while working within a fixed budget and maintaining effective team management. This stage resulted in further eliminations, leading to the final round.",
      "The concluding stage took place at Dubai Opera, where finalists delivered inspirational speeches aimed at empowering youth. The task required confident public speaking before senior officials and dignitaries, along with the ability to respond clearly and persuasively to their questions. Captain Al Marri’s performance across all stages earned him the trust of the evaluators and secured his selection as champion.",
      "Lessons in leadership and responsibility",
      "Reflecting on the experience, Captain Al Marri described the challenge as demanding yet deeply rewarding. He highlighted how it helped refine leadership skills, strengthen decision making, and build resilience under pressure. The scenarios required balanced judgement, courage, and teamwork in both emergency and non-emergency contexts.",
      "While winning the title brought a strong sense of pride, he noted that it also carried a deeper responsibility. Being chosen among all participants reinforced the importance of continuous learning, adaptability, and self-awareness.",
      "He emphasised that the challenge revealed personal strengths and capabilities that only emerged under pressure, while also reinforcing the value of teamwork, patience, and shared expertise in developing practical and impactful solutions for the future."
    ],
    "image": "/cms/news/medium_3675_346_e061ffee16.jpg"
  },
  {
    "slug": "hatta-police-commend-dubai-municipality-employee-for-honest-act",
    "title": "Hatta Police Commend Dubai Municipality Employee for Honest Act",
    "date": "2026-01-03",
    "summary": "Hatta Police Station recognised Mr Mohammad Khan, an employee of Dubai Municipality, for his honesty after he found a tourist’s bag containing important documents and promptly handed it over to the…",
    "body": [
      "Hatta Police Station recognised Mr Mohammad Khan, an employee of Dubai Municipality, for his honesty after he found a tourist’s bag containing important documents and promptly handed it over to the police.",
      "Colonel Ali Obaid Al Buduwai, Director of Hatta Police Station, presented the recognition and commended the employee for his responsible conduct and strong ethical values. The bag was later returned to its owner, who expressed his appreciation for the swift recovery of his belongings, including his passport, and praised the high level of safety and security across the UAE.",
      "Colonel Al Buduwai noted that such actions reflect the community’s moral and humanitarian values and a strong sense of social responsibility. He added that honouring positive behaviour supports efforts to promote good conduct and strengthens the country’s reputation for safety and security."
    ],
    "image": "/cms/news/medium_3141_567657_a103e795e0.jpg"
  },
  {
    "slug": "dubai-police-engage-public-and-private-sectors-to-future-proof-road-safety-and-l",
    "title": "Dubai Police Engage Public and Private Sectors to Future-Proof Road Safety and Labour",
    "date": "2026-01-03",
    "summary": "In a significant move to bolster community safety, Dubai Police, represented by Jebel Ali and Al Barsha Police Stations, recently hosted a high-level panel discussion titled Forecasting the Future of…",
    "body": [
      "In a significant move to bolster community safety, Dubai Police, represented by Jebel Ali and Al Barsha Police Stations, recently hosted a high-level panel discussion titled Forecasting the Future of Road Safety and Labour Area Security in Dubai.",
      "The session aimed to strengthen institutional integration between government and private entities, fostering a collaborative environment to share best practices and develop innovative solutions for contemporary security challenges.",
      "The event was attended by Brigadier Rashid Saleh Al Shehhi, Deputy Director of the General Department of Police Stations for Bur Dubai Police Stations Affairs; Colonel Jamal Ibrahim Ali, Director of Jebel Ali Police Station; and Colonel Yousef Thani bin Qaba, Acting Director of Al Barsha Police Station. They were joined by a diverse group of senior officers and representatives from key strategic partners, including the Ministry of Human Resources and Emiratisation, the Traffic Prosecution, the Labour Committee, the General Directorate of Residency and Foreigners Affairs (GDRFA), and the Ports, Customs and Free Zone Corporation.",
      "A Proactive Approach to Modern Challenges",
      "Brigadier Rashid Saleh Al Shehhi highlighted that Dubai Police is committed to creating a secure and sustainable environment within labour communities by deepening partnerships across sectors. He noted that modern threats, such as digital fraud and narcotics, necessitate proactive strategies rooted in innovation and community awareness. Our focus is on evolving communication channels with the labour workforce and prioritising prevention in all field operations, Brigadier Al Shehhi stated. He added that the positive engagement seen during the session reflects a shared responsibility that enhances the security system’s responsiveness, ensuring Dubai remains a premier global destination for living and working.",
      "Collaborative Strategy and Integrated Action",
      "The session facilitated a comprehensive dialogue across five pivotal themes: combating digital fraud, preventing drug proliferation, enhancing community wellbeing, eliminating bureaucracy, and reducing run-over accidents to improve overall road safety.",
      "This multi-faceted discussion drew on the expertise of an extensive range of internal and external stakeholders, including the General Departments of Traffic, Criminal Investigation, Anti-Narcotics, and Human Rights, alongside prominent private sector partners such as Dubai Holding, Dubai Industrial City, Dubai Investment Park, SK Company, Dutco Construction Group, Hosni Group of Companies, Barakat Quality Plus, Wade Adams Contracting, and Beta Logistics."
    ],
    "image": "/cms/news/medium_8879_3453454_f7158935d7.jpg"
  },
  {
    "slug": "dubai-police-seize-vehicle-fine-driver-for-dangerous-stunts-and-noise-disturbanc",
    "title": "Dubai Police Seize Vehicle, Fine Driver for Dangerous Stunts and Noise Disturbance",
    "date": "2026-01-02",
    "summary": "Dubai Police have impounded a high-performance vehicle and taken legal action against its driver following a series of reckless traffic violations captured in a viral social media video.",
    "body": [
      "Dubai Police have impounded a high-performance vehicle and taken legal action against its driver following a series of reckless traffic violations captured in a viral social media video.",
      "Brigadier Juma Salem bin Suwaidan, Acting Director of the General Department of Traffic, confirmed that traffic patrols tracked down the vehicle after it was filmed performing dangerous stunts across various locations in Dubai, posing a direct threat to public safety.",
      "The violations included driving at excessive speeds and making illegal modifications to the vehicle, which caused flames to burst from the exhaust and generated significant noise, disturbing residents and fellow motorists.",
      "The road is not a stage for stunts or risky experiments, Brigadier bin Suwaidan emphasised.",
      "Such behaviours are not only a nuisance but are extremely dangerous. Illegal modifications and reckless driving can lead to severe accidents, distract other road users, and cause a loss of vehicle control.",
      "In line with Dubai’s commitment to road safety, the vehicle was impounded under the provisions of Decree No. 30 of 2023. The driver now faces strict legal measures, including a fine of up to AED 10,000 to release the impounded vehicle. bin Suwaidan explained that Dubai Police utilise the latest technology and digital monitoring to identify offenders, whether through field patrols or by investigating content shared on social media platforms.",
      "Maintaining calm and discipline on our roads is a shared responsibility, bin Suwaidan added. We urge all motorists to respect traffic laws, avoid illegal vehicle modifications, and ensure the safety and peace of our community.",
      "Dubai Police continue to encourage the public to report dangerous driving through official channels, such as the Dubai Police Official Website, reinforcing the city’s status as a safe and civilised environment for everyone."
    ],
    "image": "/cms/news/medium_8622_234324_a9dddfd5d6.jpg"
  },
  {
    "slug": "final-call-for-elite-teams-registration-still-open-for-the-uae-swat-challenge-20",
    "title": "Final Call for Elite Teams: Registration Still Open for the UAE SWAT Challenge 2026",
    "date": "2026-01-02",
    "summary": "Dubai The organising committee for the UAE SWAT Challenge 2026 is issuing a final reminder to special police units, rapid-intervention teams, and tactical squads worldwide that registration is still…",
    "body": [
      "Dubai The organising committee for the UAE SWAT Challenge 2026 is issuing a final reminder to special police units, rapid-intervention teams, and tactical squads worldwide that registration is still open for the upcoming seventh edition.",
      "Set to take place from 7th to 11th February 2026 at the Training City in Al Ruwayyah, Dubai, this premier global event offers elite units a unique platform to test their tactical prowess, physical endurance, and operational readiness. Teams that have not yet secured their place are encouraged to do so soon to ensure sufficient time for peak performance preparation.",
      "Registration Process",
      "Elite units from around the world can still submit their details and required documentation via the official portal: www.uaeswatchallenge.com",
      "A Legacy of Tactical Excellence",
      "Since its inception in 2019, the challenge has grown from 48 participating teams to a record-breaking international spectacle. In its most recent edition, the event earned a Guinness World Record for the highest number of countries participating in a SWAT-specific tournament, with 73 teams from 46 nations competing.",
      "Five Days of Intense Competition",
      "The 2026 challenge will feature five specialised tests designed to simulate high-pressure, real-world tactical missions:",
      "Assault Tactical Operations Officer Rescue High Tower Obstacle Course",
      "Beyond the professional competition, Dubai Police welcomes the general public to attend and support the world’s elite tactical teams as they vie for top honours in one of the emirates most adrenaline-fuelled annual events."
    ],
    "image": "/cms/news/medium_6226_757_2589612516.jpg"
  }
];
