/**
 * Builds app/content-news.ts straight from the live news API — this one endpoint
 * still answers, so unlike the other content files it does not need a captured
 * payload. Run from the repo root:
 *   node scripts/gen-news.mjs
 * then mirror the images it lists:
 *   node scripts/fetch-assets.mjs scripts/news-images.txt
 */
import fs from "node:fs";

const API = "https://www.dubaipolice.gov.ae/dpcms/api/news?populate=image";
const images = new Set();

/**
 * Same /cms mirroring rule the other generators use. The record's own `url`
 * 404s on the origin; only the resized copies under strapiMedia are served, so
 * take the largest of those.
 */
function asset(image) {
  const url =
    image?.formats?.medium?.url ??
    image?.formats?.small?.url ??
    image?.formats?.thumbnail?.url ??
    image?.url;
  if (!url) return null;
  const clean = url.replace(/^\/cmsUploads\/strapiMedia\//, "").replace(/^\/cmsUploads\//, "");
  const local = "news/" + clean.split("/").pop();
  // The bare /cmsUploads path resets the connection; only /dpcms serves media.
  images.add(["/dpcms" + url, local]);
  return "/cms/" + local;
}

export const slugify = (s) =>
  s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[‘’']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);

/** The CMS separates paragraphs with runs of spaces rather than newlines. */
const paragraphs = (html) =>
  String(html ?? "")
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/g, " ")
    .split(/\s{3,}|\r?\n\s*\r?\n/)
    .map((p) => p.replace(/\s+/g, " ").trim())
    .filter(Boolean);

const res = await fetch(API, {
  headers: { accept: "application/json", "user-agent": "Mozilla/5.0 Chrome/141" },
});
const { data } = await res.json();

const seen = new Set();
const items = [];
for (const n of data) {
  const title = (n.title ?? "").trim();
  if (!title) continue; // a couple of rows come back with no headline
  const slug = slugify(title);
  if (seen.has(slug)) continue;
  seen.add(slug);

  const body = paragraphs(n.description);
  items.push({
    slug,
    title,
    date: (n.date || n.publishedAt || "").slice(0, 10),
    summary:
      body[0]?.length > 200
        ? body[0].slice(0, 200).replace(/\s+\S*$/, "") + "…"
        : (body[0] ?? ""),
    body,
    image: asset(n.image),
  });
}

fs.writeFileSync(
  "app/content-news.ts",
  `// Generated by scripts/gen-news.mjs — do not edit by hand.\n\n` +
    `export type NewsItem = {\n` +
    `  slug: string;\n  title: string;\n  date: string;\n` +
    `  summary: string;\n  body: string[];\n  image: string | null;\n};\n\n` +
    `export const news: NewsItem[] = ${JSON.stringify(items, null, 2)};\n`,
);

fs.writeFileSync(
  "scripts/news-images.txt",
  [...images].map(([remote, local]) => `${remote}\tcms/${local}`).join("\n") + "\n",
);

console.log(`${items.length} articles, ${images.size} images`);
