/**
 * Builds app/content-events.ts and app/content-albums.ts from the two CMS
 * endpoints the live site calls (both POST, both still answering). Run from the
 * repo root:
 *   node scripts/gen-media.mjs
 * then mirror the images it lists:
 *   node scripts/fetch-assets.mjs scripts/media-images.txt
 */
import fs from "node:fs";

const BASE = "https://www.dubaipolice.gov.ae/dpcms/api/";
const HEADERS = {
  accept: "application/json",
  "content-type": "application/json",
  "user-agent": "Mozilla/5.0 Chrome/141",
  origin: "https://www.dubaipolice.gov.ae",
  referer: "https://www.dubaipolice.gov.ae/app/home/media",
};

const wait = (ms) => new Promise((r) => setTimeout(r, ms));

/** The origin drops the socket on back-to-back requests, so pace and retry. */
const post = async (path, body) => {
  let last;
  for (let attempt = 0; attempt < 5; attempt += 1) {
    await wait(attempt ? 3000 * attempt : 700);
    try {
      const res = await fetch(BASE + path, {
        method: "POST",
        headers: HEADERS,
        body: JSON.stringify(body),
      });
      const json = await res.json();
      if (json.data) return json;
      last = new Error(`${path}: ${JSON.stringify(json).slice(0, 200)}`);
    } catch (err) {
      last = err;
    }
  }
  throw last;
};

/** Walks pagination_page until the reported pageCount is exhausted. */
async function all(path, body) {
  const rows = [];
  let page = 1;
  for (;;) {
    const { data, meta } = await post(path, { ...body, pagination_page: page });
    rows.push(...data);
    const pages = meta?.pagination?.pageCount ?? 1;
    if (page >= pages) return rows;
    page += 1;
  }
}

const images = new Map();

/** Mirrors under /cms; only the /dpcms-prefixed path actually serves media. */
function asset(url, folder) {
  if (!url) return null;
  const name = url.split("/").pop();
  const local = `${folder}/${name}`;
  images.set(local, "/dpcms" + url);
  return "/cms/" + local;
}

const slugify = (s) =>
  String(s)
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[‘’']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);

/** Slugs collide across years (two "flag-day" albums), so number the repeats. */
const uniquify = () => {
  const seen = new Map();
  return (slug) => {
    const n = (seen.get(slug) ?? 0) + 1;
    seen.set(slug, n);
    return n === 1 ? slug : `${slug}-${n}`;
  };
};

const text = (html) =>
  String(html ?? "")
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/g, " ")
    .split(/\n\s*\n|\s{3,}/)
    .map((p) => p.replace(/\s+/g, " ").trim())
    .filter(Boolean);

const trim = (s, n) => {
  const flat = String(s ?? "").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  return flat.length > n ? flat.slice(0, n).replace(/\s+\S*$/, "") + "…" : flat;
};

/** Location arrives as a JSON blob; only the address is worth showing. */
const address = (value) => {
  if (!value) return "";
  try {
    const parsed = typeof value === "string" ? JSON.parse(value) : value;
    return (parsed?.address ?? "").toString().trim();
  } catch {
    return typeof value === "string" ? value.trim() : "";
  }
};

/** Turns CMS enum values like exhibitions_And_Conferences into labels. */
const label = (value) =>
  String(value ?? "")
    .replace(/[_-]+/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .split(/ +/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");

const write = (file, type, name, rows) =>
  fs.writeFileSync(
    file,
    `// Generated by scripts/gen-media.mjs — do not edit by hand.\n\n${type}\n\n` +
      `export const ${name} = ${JSON.stringify(rows, null, 2)} as const;\n`,
  );

// ---------------------------------------------------------------- events

const eventSlug = uniquify();
const events = (
  await all("dp-events", { mode: "dp", locale: "en", sort: "createdAt@desc" })
)
  .filter((e) => (e.title ?? "").trim())
  .map((e) => ({
    slug: eventSlug(slugify(e.title)),
    title: e.title.trim(),
    summary: trim(e.shortDescription, 180),
    body: text(e.description),
    from: (e.fromDate || "").slice(0, 10),
    to: (e.toDate || "").slice(0, 10),
    type: label(e.eventType),
    location: address(e.location),
    price: trim(e.price, 120),
    contact: trim(e.contact, 120),
    website: (e.eventwebsiteurl ?? "").trim(),
    email: (e.eventwebemail ?? "").trim(),
    image: asset(e.image?.url, "events"),
  }));

write(
  "app/content-events.ts",
  `export type EventItem = {
  slug: string;
  title: string;
  summary: string;
  body: readonly string[];
  from: string;
  to: string;
  type: string;
  location: string;
  price: string;
  contact: string;
  website: string;
  email: string;
  image: string | null;
};`,
  "events",
  events,
);

// --------------------------------------------------------------- albums

const albumSlug = uniquify();
const albums = (
  await all("images-galleries", {
    mode: "dp",
    locale: "en",
    pagination_pageSize: 10,
    sort: "date@desc",
  })
)
  .filter((a) => (a.title ?? "").trim() && (a.media ?? []).length)
  .map((a) => ({
    slug: albumSlug(slugify(a.title)),
    title: a.title.trim(),
    date: (a.date || "").slice(0, 10),
    description: trim(a.description, 300),
    photos: a.media.map((m) => asset(m.url, "gallery")).filter(Boolean),
  }))
  .map((a) => ({ ...a, cover: a.photos[0], count: a.photos.length }));

write(
  "app/content-albums.ts",
  `export type Album = {
  slug: string;
  title: string;
  date: string;
  description: string;
  photos: readonly string[];
  cover: string;
  count: number;
};`,
  "photoAlbums",
  albums,
);

fs.writeFileSync(
  "scripts/media-images.txt",
  [...images].map(([local, remote]) => `${remote}\tcms/${local}`).join("\n") + "\n",
);

console.log(
  `${events.length} events, ${albums.length} albums ` +
    `(${albums.reduce((n, a) => n + a.count, 0)} photos), ${images.size} images`,
);
