/**
 * Strings that are identical in English and Hausa, and deliberately have no
 * dictionary entry.
 *
 * With an Arabic dictionary this file would not exist: a script test told
 * "translated" from "left in English" on its own. Hausa is written in the
 * same alphabet, so nothing distinguishes a proper noun that is correctly
 * unchanged from a line somebody forgot. Rather than pad the dictionary with
 * entries that map a string to itself — which would train the eye to ignore
 * exactly the thing the coverage test exists to catch — the names are listed
 * here once, and both scripts/test-i18n.mjs and scripts/prune-i18n.mjs read
 * the same list.
 *
 * The rule for adding something: it is a name. A road, a statute, a callsign,
 * a rank abbreviation used as an identifier, a brand. Anything that describes
 * rather than names belongs in the dictionary, translated.
 */
export const PROPER_NOUNS = new Set([
  // Institutions and brands.
  "Nigeria Police Force",
  "FCT Command",
  "POSSAP",
  "NIN",
  "NINAuth",
  "Abuja",
  "Facebook",
  "Youtube",
  "Twitter",
  "Instagram",
  "App Store",
  "Google Play",
  "App Gallery",
  "AppGallery",
  "My Nigeria Police Force",

  // Statutes, cited the way a court would cite them.
  "Police Act, 2020",
  "Nigeria Police Trust Fund (Establishment) Act, 2019",
  "Administration of Criminal Justice Act, 2015",
  "Penal Code Act, Cap. P3 LFN 2004",
  "Criminal Code Act, Cap. C38 LFN 2004",
  "Evidence Act, 2011 (as amended, 2023)",
  "Cybercrimes (Prohibition, Prevention, etc.) Act, 2015 (as amended, 2024)",
  "Violence Against Persons (Prohibition) Act, 2015",
  "Child Rights Act, 2003",
  "Trafficking in Persons (Prohibition) Enforcement and Administration Act, 2015",
  "Firearms Act, Cap. F28 LFN 2004",
  "Robbery and Firearms (Special Provisions) Act, Cap. R11 LFN 2004",
  "Explosives Act, Cap. E18 LFN 2004",
  "Private Guard Companies Act, Cap. P30 LFN 2004",
  "Terrorism (Prevention and Prohibition) Act, 2022",
  "Money Laundering (Prevention and Prohibition) Act, 2022",
  "Anti-Torture Act, 2017",
  "Nigeria Data Protection Act, 2023",
  "Federal Road Safety Commission (Establishment) Act, 2007",
  "National Road Traffic Regulations, 2012",
  "Federal Capital Territory Act, Cap. F6 LFN 2004",
  "National Drug Law Enforcement Agency Act, Cap. N30 LFN 2004",

  // Roads and districts of the Territory.
  "Nnamdi Azikiwe Expressway",
  "Umaru Musa Yar'Adua Expressway (Airport Road)",
  "Murtala Muhammed Expressway",
  "Outer Southern Expressway",
  "Outer Northern Expressway",
  "Kubwa Expressway",
  "Abuja–Keffi Expressway",
  "Abuja–Kaduna Expressway",
  "Abuja–Lokoja Highway",
  "Gwagwalada–Kwali Road",
  "Bwari–Dutse Road",
  "Dei-Dei–Zuba Road",
  "Nyanya–Karu Bypass",
  "Kuje Road",
  "Gwarinpa Expressway",
  "Bill Clinton Drive",
  "Ahmadu Bello Way",
  "Shehu Shagari Way",
  "Obafemi Awolowo Way",
  "Constitution Avenue",
  "Independence Avenue",
  "Tafawa Balewa Way, Area 11",
  "Ralph Shodeinde Street, Central Area",
  "Kur Mohammed Avenue, Central Area",
  "Herbert Macaulay Way",
  "Muhammadu Buhari Way",
  "Ibrahim Babangida Way, Maitama",
  "Airport Road service lanes, Lugbe",
  "Gudu–Apo Link",
  "Aminu Kano Crescent, Wuse II",
  "Adetokunbo Ademola Crescent, Wuse II",
  "Michael Okpara Street, Wuse Zone 5",
  "Nouakchott Street, Wuse Zone 1",
  "Nouakchott Street, Wuse II",
  "Ladoke Akintola Boulevard, Garki II",
  "Gimbiya Street, Area 11",
  "Ekukinam Street, Utako",
  "Jabi–Utako Link",
  "Lungi Street, Maitama",
  "Zambezi Crescent, Maitama",
  "Yakubu Gowon Crescent, Asokoro",
  "Durumi District roads",
  "Lokogoma District roads",
  "Gwarinpa District roads",
  "Kubwa District roads",

  // Area Councils and the station names built on them.
  "Abuja Municipal",
  "Gwagwalada",
  "Kuje",
  "Bwari",
  "Kwali",
  "Abaji",
  "Central Area Command",
  "Gwagwalada Area Command",
  "Bwari Area Command",
  "Kubwa Area Command",
  "Karu Area Command",
  "Kuje Area Command",
  "Garki Division",
  "Wuse Division",
  "Wuse II Division",
  "Maitama Division",
  "Asokoro Division",
  "Utako Division",
  "Jabi Division",
  "Life Camp Division",
  "Gwarinpa Division",
  "Karmo Division",
  "Dei-Dei Division",
  "Zuba Division",
  "Dutse-Alhaji Division",
  "Lugbe Division",
  "Apo Division",
  "Durumi Division",
  "Nyanya Division",
  "Airport Division",

  // Station addresses.
  "Area 10, Garki",
  "Secretariat Road, Gwagwalada",
  "Kubwa Road, Bwari",
  "Phase 2, Kubwa",
  "Nyanya–Karu Road, Nyanya",
  "Kuje Town, off Kuje Road",
  "Area 3, Garki",
  "Zone 3, Wuse",
  "Jabi District, off Bala Sokoto Way",
  "Life Camp, Gwarinpa",
  "3rd Avenue, Gwarinpa Estate",
  "Karmo Village, off Kubwa Expressway",
  "Dei-Dei Building Materials Market",
  "Zuba Market Road, Zuba",
  "Dutse-Alhaji, off Bwari Road",
  "FHA Estate, Lugbe",
  "Apo Legislative Quarters, Apo",
  "Durumi District, off Ahmadu Bello Way",
  "Nnamdi Azikiwe International Airport",

  // Callsigns and officer names on the operations board.
  "Patrol 04",
  "Patrol 09",
  "Patrol 12",
  "Patrol 17",
  "Patrol 21",
  "Patrol 26",
  "Traffic 07",
  "Traffic 11",
  "Marine 02",
  "Air Wing 01",
  "K9 03",
  "Cybercrime 01",
  "ASP O. Nwosu",
  "Wuse 1",

  // Labels and values that are the same string in both languages.
  "A – Z",
  "Apple Pay",
  "₦120,000",
  "NIN {id}",
]);
